/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.vehicular;

import Modelo.Dao;
import Modelo.rDetalleVehiculo;
import Modelo.rVehiculos;
import Modelo.rpuser;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.table.DefaultTableCellRenderer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import swing.xp.shapeTabbedPaneUI;
import view.Login;
import view.empleado.RegisTrabajadores;
import static view.empleado.RegisTrabajadores.tableEmpleados;
import view.entradasalidas.User;
import view.mantenimiento.Mantenimiento;

/**
 *
 * @author Dani
 */
public class RegisVehiculos extends javax.swing.JFrame {

    Dao dao = new Dao();
    public static int indice;

    static Login is;
    String ip;

    String nombreUser = Login.txtusuario.getText();

    public RegisVehiculos() {
        initComponents();

        ptable();
        ptable2();
        ptable3();
        ptable4();
        ptable5();
        ptable6();

        menubar();
        tabbedpanel();

        this.setIconImage(new ImageIcon(getClass().getResource("/images/folder-saved-search.png")).getImage());

        try {
            ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(Mantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setTitle("Registro de Vehiculos.  " + nombreUser + "@ServiciosGeneralesViviana " + "[{" + ip + "}]");

        dao.mostrarVehiculos("", "", "", "", "", "", "");
        dao.mostrarDetalleVH("", "");

        dao.mostrarSoat("");
        dao.mostrarOperatividad("");
        dao.mostrarMercancia("");
        dao.mostrarAndina("");

        indice = 0;

        if (RegisVehiculos.tablevehiculos.getRowCount() != 0) {
            tablevehiculos.setRowSelectionInterval(0, 0);
        }
// tablevehiculos.setRowSelectionInterval(0, 0);
// tabledetalle.setRowSelectionInterval(0, 0);

// tablesoat.setRowSelectionInterval(0, 0);
// tableop.setRowSelectionInterval(0, 0);
// tablemarcancia.setRowSelectionInterval(0, 0);
// tableandina.setRowSelectionInterval(0, 0);
//verFilaSeleccionada();
        int j = 1;
        cantidadRegist(j);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablevehiculos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabledetalle = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablesoat = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableop = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablemarcancia = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableandina = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btndouwn = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        cantidad = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tablevehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablevehiculos.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tablevehiculos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tablevehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablevehiculosMouseClicked(evt);
            }
        });
        tablevehiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tablevehiculosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tablevehiculos);

        jTabbedPane1.addTab("Registro de vehiculos", jScrollPane1);

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tabledetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabledetalle.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tabledetalle.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabledetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabledetalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabledetalle);

        jTabbedPane1.addTab("Detalle de vehiculo", jScrollPane2);

        tablesoat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablesoat.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tablesoat.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tablesoat);

        jTabbedPane1.addTab("Soat", jScrollPane3);

        tableop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableop.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tableop.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane4.setViewportView(tableop);

        jTabbedPane1.addTab("Operatividad", jScrollPane4);

        tablemarcancia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablemarcancia.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tablemarcancia.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(tablemarcancia);

        jTabbedPane1.addTab("Mercancia", jScrollPane5);

        tableandina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableandina.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tableandina.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane6.setViewportView(tableandina);

        jTabbedPane1.addTab("Andina", jScrollPane6);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-copy.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar_16x16.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btndouwn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-down.png"))); // NOI18N
        btndouwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndouwnActionPerformed(evt);
            }
        });

        btnup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-up.png"))); // NOI18N
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-log-out_1.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-refresh.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndouwn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btndouwn)
                    .addComponent(btnup)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 51, 255));
        cantidad.setText("jLabel1");

        jButton10.setBackground(new java.awt.Color(184, 221, 182));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brain_2.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("SAFV - SISTEMA DE ADMINISTRACIÓN DE FLOTA VEHICULAR - SERVICIOS GENERALES VIVIANA EIRL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(cantidad))
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setPreferredSize(new java.awt.Dimension(324, 29));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem2.setText("Ver");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Herramientas");
        jMenu5.add(jSeparator2);

        jMenuItem3.setText("Menu principal");
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator4);

        jMenuItem4.setText("Submenu");
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        jMenu9.setText("Sistemas");

        jMenuItem5.setText("Procesos");
        jMenu9.add(jMenuItem5);

        jMenuBar1.add(jMenu9);

        jMenu11.setText("Reportes");

        jMenuItem6.setText("Imprimir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem6);

        jMenuBar1.add(jMenu11);

        jMenu14.setText("Ayuda");

        jMenuItem7.setText("?");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem7);

        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        verfilas();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (indice == 1) {
            nuevoDVH dvh90 = new nuevoDVH();
            dvh90.setVisible(true);
            dvh90.setLocationRelativeTo(null);

        } else {
            nuevoVH vh8 = new nuevoVH();
            vh8.setVisible(true);
            vh8.setLocationRelativeTo(null);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (indice == 0) {
            SearchVeh sv = new SearchVeh();
            sv.setVisible(true);
            sv.setLocationRelativeTo(null);
        }

        if (indice == 1) {
            SearchDetalle sv = new SearchDetalle();
            sv.setVisible(true);
            sv.setLocationRelativeTo(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if (indice == 0) {

            dao.mostrarVehiculos("", "", "", "", "", "", "");

            tablevehiculos.setRowSelectionInterval(0, 0);

        }

        if (indice == 1) {
            int verfilay = tablevehiculos.getSelectedRow();
            String idy = (String) tablevehiculos.getValueAt(verfilay, 0);

            dao.mostrarDetalleVH(idy, "");
            
             if (tabledetalle.getRowCount() != 0) {
                  tabledetalle.setRowSelectionInterval(0, 0);
            }
         

        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        if (indice == 0) {
            up();
        }
        if (indice == 1) {
            up1();
        }
    }//GEN-LAST:event_btnupActionPerformed

    private void btndouwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndouwnActionPerformed
        if (indice == 0) {
            down();
        }
        if (indice == 1) {
            down1();
        }
    }//GEN-LAST:event_btndouwnActionPerformed

    private void tabledetalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabledetalleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabledetalleMouseClicked

    private void tablevehiculosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablevehiculosKeyReleased
        /*if((evt.getKeyCode()==KeyEvent.VK_DOWN) || (evt.getKeyCode()==KeyEvent.VK_UP) ){
            tableUsuarios.getSelectedRow();

        }*/

    }//GEN-LAST:event_tablevehiculosKeyReleased

    private void tablevehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablevehiculosMouseClicked
        verFilaSeleccionada();

    }//GEN-LAST:event_tablevehiculosMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        jTabbedPane1.getSelectedIndex();
        indice = jTabbedPane1.getSelectedIndex();

        int j = 1;
        if (indice == 0) {

            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            btndouwn.setEnabled(true);
            btnup.setEnabled(true);
            jButton6.setEnabled(true);
            jButton9.setEnabled(true);

            cantidadRegist(j);
        }

        if (indice == 1) {
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            btndouwn.setEnabled(true);
            btnup.setEnabled(true);
            jButton6.setEnabled(true);
            jButton9.setEnabled(true);

            if (tabledetalle.getRowCount() != 0) {
                tabledetalle.setRowSelectionInterval(0, 0);
            }
            cantidadRegist(j);

        }

        if (indice == 2) {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            btndouwn.setEnabled(false);
            btnup.setEnabled(false);
            jButton6.setEnabled(false);
            jButton9.setEnabled(false);

            tablesoat.setRowSelectionInterval(0, 0);
            cantidadRegist(j);
        }

        if (indice == 3) {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            btndouwn.setEnabled(false);
            btnup.setEnabled(false);
            jButton6.setEnabled(false);
            jButton9.setEnabled(false);

            tableop.setRowSelectionInterval(0, 0);
            cantidadRegist(j);
        }

        if (indice == 4) {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            btndouwn.setEnabled(false);
            btnup.setEnabled(false);
            jButton6.setEnabled(false);
            jButton9.setEnabled(false);

            tablemarcancia.setRowSelectionInterval(0, 0);
            cantidadRegist(j);
        }

        if (indice == 5) {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            btndouwn.setEnabled(false);
            btnup.setEnabled(false);
            jButton6.setEnabled(false);
            jButton9.setEnabled(false);

            tableandina.setRowSelectionInterval(0, 0);
            cantidadRegist(j);
        }

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked

//         panel2=false;
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
//          panel2=true;
//         panel1=false;
    }//GEN-LAST:event_jScrollPane2MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (indice == 0) {
            VReporte Vreportev = new VReporte();
            Vreportev.setVisible(true);
            Vreportev.setLocationRelativeTo(null);
        }

        if (indice == 1) {
            reporteDetalleVehiculo();
        }


    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        verfilas();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        if (indice == 0) {
            reporteVehiculo();
        }

        if (indice == 1) {
            reporteDetalleVehiculo();
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        User userxy = new User();
        userxy.setVisible(true);
        userxy.setLocationRelativeTo(null);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisVehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndouwn;
    private javax.swing.JButton btnup;
    public static javax.swing.JLabel cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable tableandina;
    public static javax.swing.JTable tabledetalle;
    public static javax.swing.JTable tablemarcancia;
    public static javax.swing.JTable tableop;
    public static javax.swing.JTable tablesoat;
    public static javax.swing.JTable tablevehiculos;
    // End of variables declaration//GEN-END:variables
public void verFilaSeleccionada() {
        int verfilax = tablevehiculos.getSelectedRow();
        String idx = (String) tablevehiculos.getValueAt(verfilax, 0);
        dao.mostrarDetalleVH(idx, "");

        dao.mostrarSoat(idx);
        dao.mostrarOperatividad(idx);
        dao.mostrarMercancia(idx);
        dao.mostrarAndina(idx);
    }

    public void menubar() {

        jMenuBar1.setUI(new BasicMenuBarUI() {
            public void paint(Graphics g, JComponent c) {
                g.setColor(new Color(184, 221, 182));

                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });
    }

    public void tabbedpanel() {

        JLabel lab = new JLabel("Registro de Vehiculos");
        lab.setPreferredSize(new Dimension(140, 35));
        jTabbedPane1.setTabComponentAt(0, lab);

        JLabel lab2 = new JLabel("Detalle de Vehiculo");
        lab2.setPreferredSize(new Dimension(140, 35));
        jTabbedPane1.setTabComponentAt(1, lab2);

        JLabel lab3 = new JLabel("Soat");
        lab3.setPreferredSize(new Dimension(60, 35));
        jTabbedPane1.setTabComponentAt(2, lab3);

        JLabel lab4 = new JLabel("Operatividad");
        lab4.setPreferredSize(new Dimension(110, 35));
        jTabbedPane1.setTabComponentAt(3, lab4);

        JLabel lab5 = new JLabel("Mercancia");
        lab5.setPreferredSize(new Dimension(110, 35));
        jTabbedPane1.setTabComponentAt(4, lab5);

        JLabel lab6 = new JLabel("Andina");
        lab6.setPreferredSize(new Dimension(110, 35));
        jTabbedPane1.setTabComponentAt(5, lab6);

        jTabbedPane1.setUI(new shapeTabbedPaneUI());

    }

    public void ptable() {

        tablevehiculos.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void ptable2() {

        tabledetalle.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void ptable3() {

        tablesoat.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void ptable4() {

        tableop.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void ptable5() {

        tableandina.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void ptable6() {

        tablemarcancia.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void up() {
        int index = 0;
        index = tablevehiculos.getSelectedRow();

        if (index > 0) {
            tablevehiculos.setRowSelectionInterval(index - 1, index - 1);
            btndouwn.setEnabled(true);
            cantidadRegist(index);

        } else {
            btnup.setEnabled(false);
            btndouwn.setEnabled(true);
        }
        verFilaSeleccionada();
    }

    public void up1() {
        int index = 0;
        index = tabledetalle.getSelectedRow();

        if (index > 0) {
            tabledetalle.setRowSelectionInterval(index - 1, index - 1);
            btndouwn.setEnabled(true);
            cantidadRegist(index);

        } else {
            btnup.setEnabled(false);
            btndouwn.setEnabled(true);
        }
    }

    public void down() {
        int index;

        index = tablevehiculos.getSelectedRow();

        if (tablevehiculos.getRowCount() > (index + 1)) {
            tablevehiculos.setRowSelectionInterval(index + 1, index + 1);
            cantidadRegist(index + 2);
            btnup.setEnabled(true);
        } else {
            btndouwn.setEnabled(false);
            btnup.setEnabled(true);

        }
        verFilaSeleccionada();
    }

    public void down1() {
        int index;
        index = tabledetalle.getSelectedRow();

        if (tabledetalle.getRowCount() > (index + 1)) {
            tabledetalle.setRowSelectionInterval(index + 1, index + 1);
            cantidadRegist(index + 2);
            btnup.setEnabled(true);
        } else {
            btndouwn.setEnabled(false);
            btnup.setEnabled(true);
        }
    }

    public void cantidadRegist(int j) {
        if (indice == 0) {
            int fila = tablevehiculos.getSelectedRow();
            int x = 0;
            for (int i = 0; i < tablevehiculos.getRowCount(); i++) {
                x++;
            }
            cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
        }

        if (indice == 1) {
            int fila = tabledetalle.getSelectedRow();
            int x = 0;
            for (int i = 0; i < tabledetalle.getRowCount(); i++) {
                x++;
            }
            cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
        }
        if (indice == 2) {
            int fila = tablesoat.getSelectedRow();
            int x = 0;
            for (int i = 0; i < tablesoat.getRowCount(); i++) {
                x++;
            }
            cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
        }

        if (indice == 3) {
            int fila = tableop.getSelectedRow();
            int x = 0;
            for (int i = 0; i < tableop.getRowCount(); i++) {
                x++;
            }
            cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
        }

        if (indice == 4) {
            int fila = tablemarcancia.getSelectedRow();
            int x = 0;
            for (int i = 0; i < tablemarcancia.getRowCount(); i++) {
                x++;
            }
            cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
        }

        if (indice == 5) {
            int fila = tableandina.getSelectedRow();
            int x = 0;
            for (int i = 0; i < tableandina.getRowCount(); i++) {
                x++;
            }
            cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
        }
    }

    public void reporteVehiculo() {
        Date fecha = new Date();

        List lista = new ArrayList();
        lista.clear();

        for (int i = 0; i < tablevehiculos.getRowCount(); i++) {

            rVehiculos mcxx = new rVehiculos(
                    tablevehiculos.getValueAt(i, 0).toString(),
                    tablevehiculos.getValueAt(i, 1).toString(),
                    tablevehiculos.getValueAt(i, 4).toString(),
                    tablevehiculos.getValueAt(i, 6).toString(),
                    tablevehiculos.getValueAt(i, 7).toString(),
                    tablevehiculos.getValueAt(i, 11).toString(),
                    tablevehiculos.getValueAt(i, 14).toString(),
                    tablevehiculos.getValueAt(i, 12).toString(),
                    tablevehiculos.getValueAt(i, 13).toString());
            lista.add(mcxx);

        }
        try {
            String master = System.getProperty("user.dir") + "/src/Reportes/rvehiculos.jasper";
//            String master = System.getProperty("user.dir") + "/src/Reportes/rptEstado.jasper";
//
            Map parametro = new HashMap();

//            parametro.put("logo", this.getClass().getResourceAsStream(logotipo));
            parametro.put("fechaAct", Utilidades.formatDate(fecha));

            JasperPrint informe = JasperFillManager.fillReport(master, parametro, new JRBeanCollectionDataSource(lista));

            JasperViewer.viewReport(informe, false);
//            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(rpuser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void reporteDetalleVehiculo() {
        Date fecha = new Date();
        List lista = new ArrayList();
        lista.clear();
        int verfilax = tablevehiculos.getSelectedRow();

        for (int i = 0; i < tabledetalle.getRowCount(); i++) {

            rDetalleVehiculo mcxx = new rDetalleVehiculo(
                    tabledetalle.getValueAt(i, 2).toString(),
                    tabledetalle.getValueAt(i, 3).toString(),
                    tabledetalle.getValueAt(i, 4).toString(),
                    tabledetalle.getValueAt(i, 5).toString(),
                    tabledetalle.getValueAt(i, 6).toString(),
                    tabledetalle.getValueAt(i, 7).toString(),
                    tabledetalle.getValueAt(i, 8).toString(),
                    tabledetalle.getValueAt(i, 9).toString(),
                    tabledetalle.getValueAt(i, 10).toString(),
                    tabledetalle.getValueAt(i, 11).toString(),
                    tabledetalle.getValueAt(i, 13).toString());
            lista.add(mcxx);
        }
        try {
            String master = System.getProperty("user.dir") + "/src/Reportes/rDetalleVehiculo.jasper";

            Map parametro = new HashMap();
//          parametro.put("logo", this.getClass().getResourceAsStream(logotipo));
            parametro.put("fechaAct", Utilidades.formatDate(fecha));

            String codigoRegistro = (String) tablevehiculos.getValueAt(verfilax, 0);
            parametro.put("codigoRegistro", codigoRegistro);
//            
            String matricula = (String) tablevehiculos.getValueAt(verfilax, 1);
            parametro.put("matricula", matricula);

            String tipovehiculo = (String) tablevehiculos.getValueAt(verfilax, 4);
            parametro.put("tipovehiculo", tipovehiculo);

            JasperPrint informe = JasperFillManager.fillReport(master, parametro, new JRBeanCollectionDataSource(lista));

            JasperViewer.viewReport(informe, false);
//            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(rpuser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void verfilas() {

        if (indice == 0) {
            int fila = tablevehiculos.getSelectedRow();
            String operario = "";
            Date fechaR = null;

            if (fila < 0) {
                JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");
            } else {

                Actualizar avh = new Actualizar();
                avh.setVisible(true);
                avh.setLocationRelativeTo(null);

                Actualizar.txtcodigo.setText(tablevehiculos.getValueAt(fila, 0).toString());
                Actualizar.txtmatricula.setText(tablevehiculos.getValueAt(fila, 1).toString());
                Actualizar.txtmaquina.setText(tablevehiculos.getValueAt(fila, 2).toString());
                Actualizar.txtplaca.setText(tablevehiculos.getValueAt(fila, 3).toString());

                String tvh = (String) tablevehiculos.getValueAt(fila, 4);
                System.out.println(tvh);
                Actualizar.cbtv.getModel().setSelectedItem(tvh);

                Actualizar.txtmarca.setText(tablevehiculos.getValueAt(fila, 5).toString());
                Actualizar.txtmodelo.setText(tablevehiculos.getValueAt(fila, 6).toString());
                Actualizar.txtserie.setText(tablevehiculos.getValueAt(fila, 7).toString());
                Actualizar.txtsm.setText(tablevehiculos.getValueAt(fila, 8).toString());
                Actualizar.txtnf.setText(tablevehiculos.getValueAt(fila, 9).toString());
                Actualizar.txtnn.setText(tablevehiculos.getValueAt(fila, 10).toString());
                Actualizar.txtres.setText(tablevehiculos.getValueAt(fila, 11).toString());

                try {
                    fechaR = new SimpleDateFormat("yyyy-MM-dd").parse((String) tablevehiculos.getValueAt(fila, 12).toString());
                } catch (ParseException ex) {
                    Logger.getLogger(RegisVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }

                Actualizar.datefr.setDate(fechaR);

                operario = tablevehiculos.getValueAt(fila, 13).toString();
                if (operario.equals("1")) {
                    Actualizar.ckoperario.setSelected(true);
                } else {
                    Actualizar.ckoperario.setSelected(false);
                }

                String funcion = (String) tablevehiculos.getValueAt(fila, 14);
                Actualizar.cbfuncion.getModel().setSelectedItem(funcion);

                Actualizar.txtfmodif.setText(tablevehiculos.getValueAt(fila, 15).toString());
                Actualizar.txtuser1.setText(tablevehiculos.getValueAt(fila, 16).toString());
                Actualizar.txtip.setText(tablevehiculos.getValueAt(fila, 17).toString());
            }
        }

        if (indice == 1) {
            int filaD = tabledetalle.getSelectedRow();
            String tarprop = "";

            if (filaD < 0) {
                JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");
            } else {

                ActualizarDetalle dvhx = new ActualizarDetalle();
                dvhx.setVisible(true);
                dvhx.setLocationRelativeTo(null);

                ActualizarDetalle.txtitem.setText(tabledetalle.getValueAt(filaD, 0).toString());
                ActualizarDetalle.txtcodigo.setText(tabledetalle.getValueAt(filaD, 1).toString());
                ActualizarDetalle.txtcolor.setText(tabledetalle.getValueAt(filaD, 2).toString());
                ActualizarDetalle.txtclase.setText(tabledetalle.getValueAt(filaD, 3).toString());
                ActualizarDetalle.txtcapm3.setText(tabledetalle.getValueAt(filaD, 4).toString());
                ActualizarDetalle.txttc.setText(tabledetalle.getValueAt(filaD, 5).toString());
                ActualizarDetalle.txteje.setText(tabledetalle.getValueAt(filaD, 6).toString());
                ActualizarDetalle.txtcargarutil.setText(tabledetalle.getValueAt(filaD, 7).toString());
                ActualizarDetalle.txtpn.setText(tabledetalle.getValueAt(filaD, 8).toString());
                ActualizarDetalle.txtlargo.setText(tabledetalle.getValueAt(filaD, 9).toString());
                ActualizarDetalle.txtancho.setText(tabledetalle.getValueAt(filaD, 10).toString());
                ActualizarDetalle.txtalto.setText(tabledetalle.getValueAt(filaD, 11).toString());
                ActualizarDetalle.txtcarroc.setText(tabledetalle.getValueAt(filaD, 12).toString());

                String tar = tabledetalle.getValueAt(filaD, 13).toString();
                if (tar.equals("1")) {
                    ActualizarDetalle.cktarp.setSelected(true);
                } else {
                    ActualizarDetalle.cktarp.setSelected(false);
                }

                ActualizarDetalle.txtns.setText(tabledetalle.getValueAt(filaD, 14).toString());
                ActualizarDetalle.txtnh.setText(tabledetalle.getValueAt(filaD, 15).toString());
                ActualizarDetalle.txtano.setText(tabledetalle.getValueAt(filaD, 16).toString());
                ActualizarDetalle.txtpotencia.setText(tabledetalle.getValueAt(filaD, 17).toString());
                ActualizarDetalle.txtgalones.setText(tabledetalle.getValueAt(filaD, 18).toString());
                ActualizarDetalle.txtfmodif.setText(tabledetalle.getValueAt(filaD, 19).toString());
                ActualizarDetalle.txtuser1.setText(tabledetalle.getValueAt(filaD, 20).toString());
                ActualizarDetalle.txtip.setText(tabledetalle.getValueAt(filaD, 21).toString());
            }
        }

        if (indice == 2) {
            int fila = tablesoat.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");
            } else {
                Date fechai = null, fechaf = null;

                aSoat as = new aSoat();
                as.setVisible(true);
                as.setLocationRelativeTo(null);

                aSoat.lblitem.setText(tablesoat.getValueAt(fila, 0).toString());
                aSoat.txtid.setText(tablesoat.getValueAt(fila, 1).toString());

                try {
                    fechai = new SimpleDateFormat("yyyy-MM-dd").parse((String) tablesoat.getValueAt(fila, 2).toString());
                } catch (ParseException ex) {
                    Logger.getLogger(RegisVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
                aSoat.jdinicio.setDate(fechai);

                try {
                    fechaf = new SimpleDateFormat("yyyy-MM-dd").parse((String) tablesoat.getValueAt(fila, 3).toString());
                } catch (ParseException ex) {
                    Logger.getLogger(RegisVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
                aSoat.jdfinal.setDate(fechaf);
            }
        }

        if (indice == 3) {
            int fila = tableop.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");
            } else {
                Date fechav = null;

                aOperatividad aop = new aOperatividad();
                aop.setVisible(true);
                aop.setLocationRelativeTo(null);

                aOperatividad.lblitem.setText(tableop.getValueAt(fila, 0).toString());
                aOperatividad.txtid.setText(tableop.getValueAt(fila, 1).toString());
                aOperatividad.txtn.setText(tableop.getValueAt(fila, 2).toString());

                try {
                    fechav = new SimpleDateFormat("yyyy-MM-dd").parse((String) tableop.getValueAt(fila, 3).toString());
                } catch (ParseException ex) {
                    Logger.getLogger(RegisVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
                aOperatividad.dv.setDate(fechav);
            }
        }

        if (indice == 4) {
            int fila = tablemarcancia.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");
            } else {
                Date fechav = null;

                aMercancia am = new aMercancia();
                am.setVisible(true);
                am.setLocationRelativeTo(null);

                aMercancia.lblitem.setText(tablemarcancia.getValueAt(fila, 0).toString());
                aMercancia.txtid.setText(tablemarcancia.getValueAt(fila, 1).toString());
                aMercancia.txtn.setText(tablemarcancia.getValueAt(fila, 2).toString());

                try {
                    fechav = new SimpleDateFormat("yyyy-MM-dd").parse((String) tablemarcancia.getValueAt(fila, 3).toString());
                } catch (ParseException ex) {
                    Logger.getLogger(RegisVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
                aMercancia.dv.setDate(fechav);
            }
        }
        if (indice == 5) {
            int fila = tableandina.getSelectedRow();
            if (fila < 0) {
                JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");
            } else {

                Date fechav = null;

                aAndina aa = new aAndina();
                aa.setVisible(true);
                aa.setLocationRelativeTo(null);

                aAndina.lblitem.setText(tableandina.getValueAt(fila, 0).toString());
                aAndina.txtid.setText(tableandina.getValueAt(fila, 1).toString());
                aAndina.txtn.setText(tableandina.getValueAt(fila, 2).toString());

                try {
                    fechav = new SimpleDateFormat("yyyy-MM-dd").parse((String) tableandina.getValueAt(fila, 3).toString());
                } catch (ParseException ex) {
                    Logger.getLogger(RegisVehiculos.class.getName()).log(Level.SEVERE, null, ex);
                }
                aAndina.dv.setDate(fechav);
            }
        }

    }
}
