/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.caja;

import Modelo.Dao;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import view.Login;

/**
 *
 * @author Dani
 */
public class ActDetalleCaja extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    Dao dao=new Dao();
    
//    public static boolean aux1=false;
//     public static boolean aux2=false;
//     public static boolean aux3=false;
     static Login is;
     String ip;
    String nombreUser = Login.txtusuario.getText();
    
    public static boolean aux3 = false;

    public ActDetalleCaja() {
        initComponents();
                   this.setIconImage(new ImageIcon(getClass().getResource("/images/network-receive.png")).getImage());

         try {
          ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(NuevoMovimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
          this.setTitle("Actualizar Detalle de CajaChica.  " + nombreUser+"@ServiciosGeneralesViviana " + "[{"+ ip +"}]" );
//         IDDETALLE.setVisible(false);
//          dao.listarConcepto(cbconcepto);
        dao.listarDocumentos(cbdocumento);
//       
//                ptable();
//        txtip.setVisible(false);
//        txtuser.setVisible(false);
//        txtfecha.setVisible(false);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btncompl = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        cbtipoactividad = new javax.swing.JComboBox<>();
        cbmonedas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtdetalle = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        datefecha = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        txtnombrecolaborador = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttipocambio = new javax.swing.JTextField();
        cbmonto1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtformapago = new javax.swing.JTextField();
        txtcodigocolaborador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cbdocumento = new javax.swing.JComboBox<>();
        txtnumero = new javax.swing.JTextField();
        txtserie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtip = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtfechaact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtfi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar Detalle de Caja");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btncompl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/applications-system.png"))); // NOI18N
        btncompl.setText("Completar");
        btncompl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomplActionPerformed(evt);
            }
        });
        btncompl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btncomplKeyTyped(evt);
            }
        });

        jLabel2.setText("Tipo de Actividad");

        jLabel3.setText("Monto");

        txtmonto.setEditable(false);
        txtmonto.setText("0.00");
        txtmonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontoKeyTyped(evt);
            }
        });

        cbtipoactividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Egreso" }));
        cbtipoactividad.setEnabled(false);
        cbtipoactividad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbtipoactividadFocusGained(evt);
            }
        });
        cbtipoactividad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbtipoactividadKeyTyped(evt);
            }
        });

        cbmonedas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLES" }));
        cbmonedas.setEnabled(false);
        cbmonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmonedasActionPerformed(evt);
            }
        });

        jLabel13.setText("Detalle");

        txtdetalle.setEditable(false);
        txtdetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdetalleActionPerformed(evt);
            }
        });
        txtdetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdetalleKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdetalleKeyTyped(evt);
            }
        });

        jLabel18.setText("Tipo de cambio");

        txtcodigo.setEditable(false);

        jLabel15.setText("Cuenta");

        datefecha.setEnabled(false);

        jLabel17.setText("Fecha");

        txtnombrecolaborador.setEditable(false);
        txtnombrecolaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrecolaboradorActionPerformed(evt);
            }
        });
        txtnombrecolaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombrecolaboradorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrecolaboradorKeyTyped(evt);
            }
        });

        jLabel21.setText("Colaborador");

        jLabel4.setText("Moneda");

        txttipocambio.setEditable(false);
        txttipocambio.setText("0.00");
        txttipocambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttipocambioKeyTyped(evt);
            }
        });

        cbmonto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02" }));
        cbmonto1.setEnabled(false);

        jLabel5.setText("Forma de pago");

        txtformapago.setEditable(false);
        txtformapago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtformapagoActionPerformed(evt);
            }
        });
        txtformapago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtformapagoKeyTyped(evt);
            }
        });

        txtcodigocolaborador.setEditable(false);
        txtcodigocolaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigocolaboradorActionPerformed(evt);
            }
        });
        txtcodigocolaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigocolaboradorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigocolaboradorKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-users.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Documento");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-copy.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbdocumento.setEnabled(false);
        cbdocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbdocumentoFocusGained(evt);
            }
        });
        cbdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbdocumentoKeyTyped(evt);
            }
        });

        txtnumero.setEditable(false);
        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });

        txtserie.setEditable(false);
        txtserie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtserieKeyTyped(evt);
            }
        });

        jLabel11.setText("Serie");

        jLabel12.setText("Número");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtip.setEditable(false);
        txtip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipActionPerformed(evt);
            }
        });

        txtuser.setEditable(false);

        txtfechaact.setEditable(false);

        jLabel9.setText("Fecha de Actualización");

        jLabel22.setText("Usuario");

        jLabel23.setText("Ip");

        txtnombre.setEditable(false);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtfi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfiActionPerformed(evt);
            }
        });

        jLabel16.setText("Id");

        lblid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblid.setForeground(new java.awt.Color(0, 51, 255));
        lblid.setText("idcuenta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtfi, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtcodigo)
                                        .addGap(1, 1, 1)
                                        .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(5, 5, 5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbtipoactividad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbmonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtformapago))
                                    .addComponent(txtdetalle)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addGap(1, 1, 1)
                                        .addComponent(cbmonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttipocambio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(datefecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtcodigocolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtnombrecolaborador)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtfechaact, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btncompl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblid)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lblid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datefecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcodigocolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21))
                            .addComponent(txtnombrecolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfechaact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbmonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttipocambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbmonto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtformapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbtipoactividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(btncompl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtfi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        // El código que agrega el componente al contenedor superior - no se muestra aquí
        datefecha.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                //Aquí agregaremos la funcionalidad que queremos
                /* edad();
                txtedad.setText(ed);*/

                obtenerFecha();
                // JOptionPane.showMessageDialog(rootPane, "la fecha es "+new Date());
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncomplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomplActionPerformed
        Completar completar=new Completar();
        completar.setVisible(true);
        completar.setLocationRelativeTo(null);
        
//        nuevo=true;
//
//        if (!Utilidades.isDecimal(txtmonto.getText())) {
//            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor numerico");
//            txtmonto.setText("");
//            txtmonto.grabFocus();
//            return;
//        }
//
//        double precio = Double.parseDouble(txtmonto.getText());
//        if ((precio <= 0) || (precio<=0.00)) {
//            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor mayor a cero");
//            txtmonto.setText("");
//            txtmonto.grabFocus();
//            return;
//        }
//
//        DetCaja dt=new DetCaja();
//
//        dt.setIDAPERTURA(txtcodigo.getText());
//        dt.setNOMBRE(txtnombre.getText());
//        dt.setDETALLE(txtdetalle.getText());
//
//        String valor = cbdocumento.getSelectedItem().toString();
//        dt.setIDDOCUMENTO(dao.verificarDocumento(valor));
//
//        dt.setSERIE(txtserie.getText());
//        dt.setNUMERO(txtnumero.getText());
//        if(datefecha.getDate()==null){
//            txtfi.setText("");
//        }
//        dt.setFECHAINGRESO(txtfi.getText());
//        dt.setTIPO(cbtipoactividad.getSelectedItem().toString());
//        dt.setIDCOLABORADOR(txtcodigocolaborador.getText());
//        dt.setCOLABORADOR(txtnombrecolaborador.getText());
//        dt.setTIPOCAMBIO(Double.parseDouble(txttipocambio.getText()));
//        dt.setMONEDA(cbmonedas.getSelectedItem().toString());
//        dt.setFORMAPAGO(txtformapago.getText());
//        dt.setMONTO(Double.parseDouble(txtmonto.getText()));
//    
//        dt.setFECHAACT(txtfechaact.getText());
//        dt.setUSU(txtuser.getText());
//        dt.setIP(txtip.getText());
//
//        if(nuevo){
//            resultado=dao.GuardarDetalleCaja(dt);
//            JOptionPane.showMessageDialog(rootPane, resultado);
//
//            //                    String codigov=txtcodigo.getText();
//            //                    String fechav=lblfecha.getText();
//            //
//            //           dao.mostrarDetalleCaja(codigov, fechav);
//            //                           tabledetallecaja.setRowSelectionInterval(0, 0);
//            //
//            //           totales();
//            //           quitarColor();
//            //           btncompl.setEnabled(false);
//            ////           enableFalse();
//            //           btnnuevo.setEnabled(true);
//            //
//            //           ApCaja apc=new ApCaja();
//            //           apc.setIDAPERTURA(txtcodigo.getText());
//            //           apc.setSALDO(Double.parseDouble(txtsaldofinal.getText()));
//            //           apc.setSALDOFINAL(Double.parseDouble(txtsaldofinal.getText()));
//            //           apc.setEGRESOS(Double.parseDouble(txtegresos.getText()));
//            //           apc.setINGRESOS(Double.parseDouble(txtingresos.getText()));
//            //
//            //           dao.ModificarApCaja(apc);
//        }

    }//GEN-LAST:event_btncomplActionPerformed

    private void btncomplKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncomplKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            btncompl.doClick();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btncomplKeyTyped

    private void txtmontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            //                txtobservacion.grabFocus();
        }

        cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
            dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontoKeyTyped

    private void cbtipoactividadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbtipoactividadFocusGained
        cbtipoactividad.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoactividadFocusGained

    private void cbtipoactividadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbtipoactividadKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            txtmonto.grabFocus();
        }

        cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
            dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoactividadKeyTyped

    private void cbmonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmonedasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmonedasActionPerformed

    private void txtdetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdetalleActionPerformed

    }//GEN-LAST:event_txtdetalleActionPerformed

    private void txtdetalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdetalleKeyReleased
        String cadena= (txtdetalle.getText()).toUpperCase();
        txtdetalle.setText(cadena);
    }//GEN-LAST:event_txtdetalleKeyReleased

    private void txtdetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdetalleKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            cbdocumento.grabFocus();
        }

        cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
            dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtdetalleKeyTyped

    private void txtnombrecolaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrecolaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecolaboradorActionPerformed

    private void txtnombrecolaboradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrecolaboradorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecolaboradorKeyReleased

    private void txtnombrecolaboradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrecolaboradorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecolaboradorKeyTyped

    private void txttipocambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttipocambioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipocambioKeyTyped

    private void txtformapagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtformapagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtformapagoActionPerformed

    private void txtformapagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtformapagoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtformapagoKeyTyped

    private void txtcodigocolaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigocolaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigocolaboradorActionPerformed

    private void txtcodigocolaboradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigocolaboradorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigocolaboradorKeyReleased

    private void txtcodigocolaboradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigocolaboradorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigocolaboradorKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
               BuscarColaborador bcxx=new BuscarColaborador();
               bcxx.setVisible(true);
               bcxx.setLocationRelativeTo(null); 
               aux3=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DocumentosC docc=new DocumentosC();
        docc.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbdocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbdocumentoFocusGained
        cbdocumento.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_cbdocumentoFocusGained

    private void cbdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbdocumentoKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            txtserie.grabFocus();
        }

        cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
            dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cbdocumentoKeyTyped

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            cbtipoactividad.grabFocus();
        }

        cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
            dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroKeyTyped

    private void txtserieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserieKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
            txtnumero.grabFocus();
        }

        cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
            dispose();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtserieKeyTyped

    private void txtipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtipActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtfiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActDetalleCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActDetalleCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActDetalleCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActDetalleCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActDetalleCaja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncompl;
    public static javax.swing.JComboBox<String> cbdocumento;
    public static javax.swing.JComboBox<String> cbmonedas;
    public static javax.swing.JComboBox<String> cbmonto1;
    public static javax.swing.JComboBox<String> cbtipoactividad;
    public static com.toedter.calendar.JDateChooser datefecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblid;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtcodigocolaborador;
    public static javax.swing.JTextField txtdetalle;
    public static javax.swing.JTextField txtfechaact;
    public static javax.swing.JTextField txtfi;
    public static javax.swing.JTextField txtformapago;
    public static javax.swing.JTextField txtip;
    public static javax.swing.JTextField txtmonto;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtnombrecolaborador;
    public static javax.swing.JTextField txtnumero;
    public static javax.swing.JTextField txtserie;
    public static javax.swing.JTextField txttipocambio;
    public static javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
   
//    public void ptable(){
//	
//tabledetallecaja2.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){
//
//        @Override
//        public Component getTableCellRendererComponent(JTable table, Object value,
//                boolean isSelected, boolean hasFocus, int row, int column) {
//
//            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
//
//            l.setBorder(new LineBorder(new Color(239,242,210), 1));
//
////            l.setBackground(Color.green);
////                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
//                 l.setBackground(new Color(184,221,182)); 
//               
//l.setHorizontalAlignment(SwingConstants.CENTER) ;
//
//            return l;
//        }
//    });
//	
//} 
    
    public void  obtenerFecha(){
         String rx1 = Utilidades.formatDate(datefecha.getDate());
        txtfi.setText(rx1);
    }
}
