/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.caja;

import Modelo.Dao;
import Modelo.Documentos;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Dani
 */
public class DocumentosC extends javax.swing.JFrame {

    /**
     * Creates new form RegistCaja
     */
     Dao dao=new Dao();
       boolean nuevo=false;
    boolean estado1=false,estado2=false;
    public DocumentosC() {
        initComponents();
        ptable();
         dao.mostrarDocumentos();
           tabladocumento.setRowSelectionInterval(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabladocumento = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdl = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();

        jButton1.setText("Guardar");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabladocumento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabladocumento.setSelectionBackground(new java.awt.Color(255, 255, 51));
        tabladocumento.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tabladocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabladocumentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabladocumento);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Codigo");

        txtcodigo.setEditable(false);

        jLabel2.setText("Concepto");

        txtdc.setEditable(false);

        jLabel3.setText("Descripción");

        txtdl.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtdc, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(txtdl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtdl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-refresh.png"))); // NOI18N
        btnactualizar.setEnabled(false);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_16x16.png"))); // NOI18N
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Check_16x16.png"))); // NOI18N
        btnguardar.setEnabled(false);
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-copy_1.png"))); // NOI18N
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnnuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnactualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnguardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnguardar)
                    .addComponent(btncancelar)
                    .addComponent(btnnuevo)
                    .addComponent(btnactualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        txtdc.setEditable(true);
       txtdl.setEditable(true);
 
       
           txtdc.setBackground(new Color(255,255,153));
          txtdl.setBackground(new Color(255,255,153));
          
            btncancelar.setEnabled(true);
          btnguardar.setEnabled(true);
           btnnuevo.setEnabled(false);
            btnactualizar.setEnabled(false);
            
            estado1=false;
          estado2=true;
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
  txtdc.setText("");
       txtdl.setText("");
       txtcodigo.setText("");
       
         txtdc.setEditable(false);
       txtdl.setEditable(false);
       
     
       
           txtdc.setBackground(new Color(255,255,255));
          txtdl.setBackground(new Color(255,255,255));
        
        btncancelar.setEnabled(false);
          btnguardar.setEnabled(false);
           btnnuevo.setEnabled(true);
            btnactualizar.setEnabled(false);
            
            
            
            
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
         if(estado1){
                      Documentos doc=new Documentos();  
 
            if (txtdc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar la descripción");
            txtdc.grabFocus();
            return;
        }
            
              if (txtdl.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar la descripción");
            txtdl.grabFocus();
            return;
        } 
              
        doc.setDescripcioncorta(txtdc.getText());
        doc.setDescripcionlarga(txtdl.getText());
			

					nuevo = true;
					if (nuevo) {
						String resultado = dao.GuardarDocumento(doc);
						JOptionPane.showMessageDialog(rootPane, resultado);
                                                
                                                dao.mostrarDocumentos();
                                                tabladocumento.setRowSelectionInterval(0, 0);
                                                
                                                   txtcodigo.setText("");
                                                    txtdc.setText("");
                                                    txtdl.setText("");

                                                        txtdc.setBackground(new Color(255,255,255));
                                                       txtdl.setBackground(new Color(255,255,255));
                                                       
                                                      txtdc.setEditable(false);
                                                    txtdl.setEditable(false);
                                                    
                                                     btncancelar.setEnabled(false);
          btnguardar.setEnabled(false);
           btnnuevo.setEnabled(true);
            btnactualizar.setEnabled(false);
                                                    
                                                        dao.listarDocumentos(NuevoMovimiento.cbdocumento);

					}
                }
                
                 if(estado2){
                 Documentos doc=new Documentos();  
 
            if (txtdc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar la descripción");
            txtdc.grabFocus();
            return;
        }
            
              if (txtdl.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar la descripción");
            txtdl.grabFocus();
            return;
        } 
              
        doc.setIddocumentos(Integer.parseInt(txtcodigo.getText()));
        doc.setDescripcioncorta(txtdc.getText());
        doc.setDescripcionlarga(txtdl.getText());
			

					nuevo = true;
					if (nuevo) {
						String resultado = dao.ActualizarDocumento(doc);
						JOptionPane.showMessageDialog(rootPane, resultado);
                                                
                                                dao.mostrarDocumentos();
                                                tabladocumento.setRowSelectionInterval(0, 0);
                                                
                                                   

                                                        txtdc.setBackground(new Color(255,255,255));
                                                       txtdl.setBackground(new Color(255,255,255));
                                                       
                                                      txtdc.setEditable(false);
                                                    txtdl.setEditable(false);
                                                     btncancelar.setEnabled(false);
          btnguardar.setEnabled(false);
           btnnuevo.setEnabled(true);
            btnactualizar.setEnabled(false);
                                                        dao.listarDocumentos(NuevoMovimiento.cbdocumento);

					}

                }
                
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
          txtdc.setEditable(true);
       txtdl.setEditable(true);
       
       txtcodigo.setText("");
       txtdc.setText("");
       txtdl.setText("");
       
           txtdc.setBackground(new Color(255,255,153));
          txtdl.setBackground(new Color(255,255,153));
          
            btncancelar.setEnabled(true);
          btnguardar.setEnabled(true);
           btnnuevo.setEnabled(false);
            btnactualizar.setEnabled(false);
            
            
            estado1=true;
          estado2=false;

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void tabladocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabladocumentoMouseClicked
  int fila = tabladocumento.getSelectedRow();
        String id = (String)  tabladocumento.getValueAt(fila, 0);
       String dc = (String) tabladocumento.getValueAt(fila, 1);
       String dl = (String) tabladocumento.getValueAt(fila, 2);
                

                txtcodigo.setText(id);
                  txtdc.setText(dc);
                  txtdl.setText(dl);
                              btnactualizar.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_tabladocumentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DocumentosC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DocumentosC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DocumentosC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DocumentosC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocumentosC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabladocumento;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtdc;
    private javax.swing.JTextField txtdl;
    // End of variables declaration//GEN-END:variables
public void ptable(){
	
tabladocumento.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            l.setBorder(new LineBorder(new Color(239,242,210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                 l.setBackground(new Color(184,221,182)); 
               
l.setHorizontalAlignment(SwingConstants.CENTER) ;

            return l;
        }
    });
	
}}
