/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.caja;

import Modelo.ApCaja;
import Modelo.Dao;
import Modelo.DetCaja;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import view.Login;

/**
 *
 * @author Dani
 */
public class NuevoMovimiento extends javax.swing.JFrame {

    /**
     * Creates new form NuevoMovimiento
     */
    Dao dao=new Dao();
    String resultado="";
    boolean nuevo=false;
    Date fecha=new Date();
    
    static Login is;
    String nombreUser = Login.txtusuario.getText();
    String ip;
    public static boolean aux6=false;
    
    public NuevoMovimiento() {
        initComponents();
        
        ptable();
         this.setIconImage(new ImageIcon(getClass().getResource("/images/edit-copy.png")).getImage());
        darColor();
      
        txtcodigo.setText(dao.retornarIDAPERTURA(Utilidades.formatDate(fecha)));
        txtnombre.setText(dao.retornarnombre(Utilidades.formatDate(fecha)));
        txtdate.setText(Utilidades.formatDate(fecha));
          
        txtfechaact.setText(Utilidades.formatDate(fecha));
        txtuser.setText(nombreUser);
          
        
       try {
            txtip.setText(InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName());
        } catch (UnknownHostException ex) {
            Logger.getLogger(NuevoMovimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
       
       
         try {
          ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(NuevoMovimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
          this.setTitle("Nuevo Movimiento de CajaChica.  " + nombreUser+"@ServiciosGeneralesViviana " + "[{"+ ip +"}]" );
     
       
   

        dao.listarDocumentos(cbdocumento);
   
          
        if(tabledc.getRowCount() != 0){
            String id =txtcodigo.getText();
            String fechaingreso = Utilidades.formatDate(fecha);
            
            dao.mostrarDetalleCaja(id,fechaingreso);
//            tabledc.setRowSelectionInterval(0, 0);
            totales();
        }   

                   

        
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtsaldofinal = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtegresos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtingresos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledc = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btncompl = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmonto = new javax.swing.JTextField();
        cbtipoactividad = new javax.swing.JComboBox<>();
        cbmonedas = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txtdetalle = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtnombrecolaborador = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txttipocambio = new javax.swing.JTextField();
        cbmonto1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtformapago = new javax.swing.JTextField();
        txtcodigocolaborador = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        cbdocumento = new javax.swing.JComboBox<>();
        txtnumero = new javax.swing.JTextField();
        txtserie = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtip = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        txtfechaact = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtnombre = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtsaldofinal.setEditable(false);

        jLabel14.setText("Saldo Final");

        txtegresos.setEditable(false);

        jLabel20.setText("Egresos");

        txtingresos.setEditable(false);

        jLabel19.setText("Ingresos");

        jLabel16.setText("Total del dia:");

        tabledc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tabledc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabledc.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tabledc.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tabledc);

        btnnuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/format-justify-fill.png"))); // NOI18N
        btnnuevo.setText("Nuevo Documento");
        btnnuevo.setEnabled(false);
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtingresos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtegresos, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtsaldofinal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtingresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtegresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtsaldofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btncompl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/applications-system.png"))); // NOI18N
        btncompl.setText("Grabar");
        btncompl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomplActionPerformed(evt);
            }
        });
        btncompl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btncomplKeyTyped(evt);
            }
        });

        jLabel2.setText("Tipo de Actividad");

        jLabel3.setText("Monto");

        txtmonto.setText("0.00");
        txtmonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmontoKeyTyped(evt);
            }
        });

        cbtipoactividad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingreso", "Egreso" }));
        cbtipoactividad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbtipoactividadFocusGained(evt);
            }
        });
        cbtipoactividad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbtipoactividadKeyTyped(evt);
            }
        });

        cbmonedas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOLES" }));
        cbmonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmonedasActionPerformed(evt);
            }
        });

        jLabel13.setText("Detalle");

        txtdetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdetalleActionPerformed(evt);
            }
        });
        txtdetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdetalleKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdetalleKeyTyped(evt);
            }
        });

        jLabel18.setText("Tipo de cambio");

        txtcodigo.setEditable(false);

        jLabel15.setText("Cuenta");

        jLabel17.setText("Fecha");

        txtnombrecolaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrecolaboradorActionPerformed(evt);
            }
        });
        txtnombrecolaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombrecolaboradorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrecolaboradorKeyTyped(evt);
            }
        });

        jLabel21.setText("Colaborador");

        jLabel4.setText("Moneda");

        txttipocambio.setText("0.00");
        txttipocambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttipocambioKeyTyped(evt);
            }
        });

        cbmonto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02" }));

        jLabel5.setText("Forma de pago");

        txtformapago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtformapagoActionPerformed(evt);
            }
        });
        txtformapago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtformapagoKeyTyped(evt);
            }
        });

        txtcodigocolaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigocolaboradorActionPerformed(evt);
            }
        });
        txtcodigocolaborador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcodigocolaboradorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodigocolaboradorKeyTyped(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-users.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Documento");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-copy.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbdocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbdocumentoFocusGained(evt);
            }
        });
        cbdocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbdocumentoKeyTyped(evt);
            }
        });

        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });

        txtserie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtserieKeyTyped(evt);
            }
        });

        jLabel11.setText("Serie");

        jLabel12.setText("Número");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(txtserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        txtip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipActionPerformed(evt);
            }
        });

        jLabel9.setText("Fecha de Actualización");

        jLabel22.setText("Usuario");

        jLabel23.setText("Ip");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-find.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtnombre.setEditable(false);
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
        });

        txtdate.setEditable(false);
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        txtdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdateKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdateKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbtipoactividad, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbmonto1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtformapago))
                            .addComponent(txtdetalle)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(1, 1, 1)
                                .addComponent(cbmonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttipocambio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtdate, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigocolaborador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnombrecolaborador)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfechaact, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btncompl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtcodigocolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21))
                            .addComponent(txtnombrecolaborador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfechaact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel3)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(cbmonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txttipocambio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbmonto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtformapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(cbtipoactividad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btncompl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addGap(18, 24, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncomplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomplActionPerformed


          nuevo=true;
          
          if (!Utilidades.isDecimal(txtmonto.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor numerico");
            txtmonto.setText("");
            txtmonto.grabFocus();
            return;
        }
               
         double precio = Double.parseDouble(txtmonto.getText());
         if ((precio <= 0) || (precio<=0.00)) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor mayor a cero");
            txtmonto.setText("");
            txtmonto.grabFocus();
            return;
        } 
        
        DetCaja dt=new DetCaja();
            
            dt.setIDAPERTURA(txtcodigo.getText());
            dt.setNOMBRE(txtnombre.getText());
            dt.setDETALLE(txtdetalle.getText());
                        
            String valor = cbdocumento.getSelectedItem().toString();
            dt.setIDDOCUMENTO(dao.verificarDocumento(valor));
            
            dt.setSERIE(txtserie.getText());
            dt.setNUMERO(txtnumero.getText());
           
            dt.setFECHAINGRESO(txtdate.getText());
            dt.setTIPO(cbtipoactividad.getSelectedItem().toString());
            dt.setIDCOLABORADOR(txtcodigocolaborador.getText());
            dt.setCOLABORADOR(txtnombrecolaborador.getText());
            dt.setTIPOCAMBIO(Double.parseDouble(txttipocambio.getText()));
            dt.setMONEDA(cbmonedas.getSelectedItem().toString());
            dt.setFORMAPAGO(txtformapago.getText());
            dt.setMONTO(Double.parseDouble(txtmonto.getText()));         
            dt.setFECHAACT(txtfechaact.getText());
            dt.setUSU(txtuser.getText());
            dt.setIP(txtip.getText());
            
        if(nuevo){
                resultado=dao.GuardarDetalleCaja(dt);
                JOptionPane.showMessageDialog(rootPane, resultado);
  
//                Date fecha=new Date();
                String id = txtcodigo.getText();
                String fechaingreso = Utilidades.formatDate(fecha);
//                dao.mostrarCaja(id, fechaingreso,"");
                
                
                dao.mostrarDetalleCaja(id, fechaingreso);
  
//                    String codigov=txtcodigo.getText();
//                    String fechav=lblfecha.getText();
//
//           dao.mostrarDetalleCaja(codigov, fechav);
                           tabledc.setRowSelectionInterval(0, 0);
//
           totales();
           quitarColor();
           enableFalse();
           btncompl.setEnabled(false);
          
           btnnuevo.setEnabled(true);
//           
           ApCaja apc=new ApCaja();
           apc.setIDAPERTURA(txtcodigo.getText());
           apc.setSALDO(Double.parseDouble(txtsaldofinal.getText()));
           apc.setSALDOFINAL(Double.parseDouble(txtsaldofinal.getText()));
           apc.setEGRESOS(Double.parseDouble(txtegresos.getText()));
           apc.setINGRESOS(Double.parseDouble(txtingresos.getText()));
            
           dao.ModificarApCaja(apc);
        }


    }//GEN-LAST:event_btncomplActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
             darColor();
                enableTrue();
                limpiar();
                darColor();
                btncompl.setEnabled(true);
                btnnuevo.setEnabled(false);

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void txtdetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdetalleActionPerformed
      
    }//GEN-LAST:event_txtdetalleActionPerformed

    private void txtdetalleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdetalleKeyReleased
         String cadena= (txtdetalle.getText()).toUpperCase();
txtdetalle.setText(cadena);
    }//GEN-LAST:event_txtdetalleKeyReleased

    private void txtdetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdetalleKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
               cbdocumento.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtdetalleKeyTyped

    private void cbdocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbdocumentoKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtserie.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_cbdocumentoKeyTyped

    private void txtserieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserieKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtnumero.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtserieKeyTyped

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                cbtipoactividad.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtnumeroKeyTyped

    private void cbtipoactividadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbtipoactividadKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtmonto.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoactividadKeyTyped

    private void txtmontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmontoKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
//                txtobservacion.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtmontoKeyTyped

    private void btncomplKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btncomplKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
               btncompl.doClick();
            }
        
           // TODO add your handling code here:
    }//GEN-LAST:event_btncomplKeyTyped

    private void cbdocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbdocumentoFocusGained
cbdocumento.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_cbdocumentoFocusGained

    private void cbtipoactividadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbtipoactividadFocusGained
cbtipoactividad.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipoactividadFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
               DocumentosC docc=new DocumentosC();
               docc.setVisible(true);
               docc.setLocationRelativeTo(null);    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtnombrecolaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrecolaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecolaboradorActionPerformed

    private void txtnombrecolaboradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrecolaboradorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecolaboradorKeyReleased

    private void txtnombrecolaboradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrecolaboradorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrecolaboradorKeyTyped

    private void txttipocambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttipocambioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipocambioKeyTyped

    private void txtformapagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtformapagoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtformapagoKeyTyped

    private void txtformapagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtformapagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtformapagoActionPerformed

    private void txtcodigocolaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigocolaboradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigocolaboradorActionPerformed

    private void txtcodigocolaboradorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigocolaboradorKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigocolaboradorKeyReleased

    private void txtcodigocolaboradorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodigocolaboradorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigocolaboradorKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BuscarColaborador bcq=new BuscarColaborador();
               bcq.setVisible(true);
               bcq.setLocationRelativeTo(null); 
               aux6=true;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtipActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           BuscarCuenta bcccc=new BuscarCuenta();
               bcccc.setVisible(true);
               bcccc.setLocationRelativeTo(null); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyTyped

    private void cbmonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmonedasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmonedasActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void txtdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateKeyReleased

    private void txtdateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoMovimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoMovimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncompl;
    private javax.swing.JButton btnnuevo;
    public static javax.swing.JComboBox<String> cbdocumento;
    private javax.swing.JComboBox<String> cbmonedas;
    private javax.swing.JComboBox<String> cbmonto1;
    private javax.swing.JComboBox<String> cbtipoactividad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tabledc;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtcodigocolaborador;
    public static javax.swing.JTextField txtdate;
    public static javax.swing.JTextField txtdetalle;
    private javax.swing.JTextField txtegresos;
    private javax.swing.JTextField txtfechaact;
    private javax.swing.JTextField txtformapago;
    private javax.swing.JTextField txtingresos;
    private javax.swing.JTextField txtip;
    private javax.swing.JTextField txtmonto;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtnombrecolaborador;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtsaldofinal;
    private javax.swing.JTextField txtserie;
    private javax.swing.JTextField txttipocambio;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
    public void ptable(){
	
tabledc.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            l.setBorder(new LineBorder(new Color(239,242,210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                 l.setBackground(new Color(184,221,182)); 
               
l.setHorizontalAlignment(SwingConstants.CENTER) ;

            return l;
        }
    });
	
} 
    private void totales() {
        int num = tabledc.getRowCount();
        double sumVal = 0, sumIngr=0, sumEgr=0;
        for (int i = 0; i < num; i++) {
            //fila y columna
           // sumCant += Utilidades.objectToDouble(tabledetallecaja.getValueAt(i, 3));
            sumVal += Utilidades.objectToDouble(tabledc.getValueAt(i, 6));
            
           String mov= tabledc.getValueAt(i, 4).toString();
           //System.out.println(dd);
           if(mov.equals("Ingreso")){
               sumIngr += Utilidades.objectToDouble(tabledc.getValueAt(i, 6));
           }
            if(mov.equals("Egreso")){
               sumEgr += Utilidades.objectToDouble(tabledc.getValueAt(i, 6));
           }
        }
        txtsaldofinal.setText("" + sumVal);
        txtingresos.setText("" + sumIngr);
        txtegresos.setText("" + sumEgr);
       
        //txtTotalValor.setText("" + sumVal);
    }
    
   public void darColor(){
            txtcodigo.setBackground(new Color(255,255,153));
            txtnombre.setBackground(new Color(255,255,153));
            txtdetalle.setBackground(new Color(255,255,153));
            cbdocumento.setBackground(new Color(255,255,153));
            txtserie.setBackground(new Color(255,255,153));
            txtnumero.setBackground(new Color(255,255,153));
            txtdate.setBackground(new Color(255,255,153));
            cbtipoactividad.setBackground(new Color(255,255,153));
            txtcodigocolaborador.setBackground(new Color(255,255,153));
            txtnombrecolaborador.setBackground(new Color(255,255,153));
            txttipocambio.setBackground(new Color(255,255,153));
            cbmonedas.setBackground(new Color(255,255,153));
            txtformapago.setBackground(new Color(255,255,153));
            txtmonto.setBackground(new Color(255,255,153));
                 
            
            
          
   }
    public void quitarColor(){
               txtcodigo.setBackground(new Color(255,255,255));
            txtnombre.setBackground(new Color(255,255,255));
            txtdetalle.setBackground(new Color(255,255,255));
            cbdocumento.setBackground(new Color(255,255,255));
            txtserie.setBackground(new Color(255,255,255));
            txtnumero.setBackground(new Color(255,255,255));
            txtdate.setBackground(new Color(255,255,255));
            cbtipoactividad.setBackground(new Color(255,255,255));
            txtcodigocolaborador.setBackground(new Color(255,255,255));
            txtnombrecolaborador.setBackground(new Color(255,255,255));
            txttipocambio.setBackground(new Color(255,255,255));
            cbmonedas.setBackground(new Color(255,255,255));
            txtformapago.setBackground(new Color(255,255,255));
            txtmonto.setBackground(new Color(255,255,255));
          
   }
     public void enableFalse(){
//            txtcodigo.setEditable(false);
//            txtnombre.setEditable(false);
            txtdetalle.setEditable(false);
            cbdocumento.setEnabled(false);
            txtserie.setEditable(false);
            txtnumero.setEditable(false);
//            txtfii.setEditable(false);
            cbtipoactividad.setEnabled(false);
            txtcodigocolaborador.setEditable(false);
            txtnombrecolaborador.setEditable(false);
            txttipocambio.setEditable(false);
            cbmonedas.setEnabled(false);
            txtformapago.setEditable(false);
            txtmonto.setEditable(false);      
   }
    
       public void enableTrue(){
//            txtcodigo.setEditable(true);
//            txtnombre.setEditable(true);
            txtdetalle.setEditable(true);
            cbdocumento.setEnabled(true);
            txtserie.setEditable(true);
            txtnumero.setEditable(true);
//            txtfii.setEditable(true);
            cbtipoactividad.setEnabled(true);
            txtcodigocolaborador.setEditable(true);
            txtnombrecolaborador.setEditable(true);
            txttipocambio.setEditable(true);
            cbmonedas.setEnabled(true);
            txtformapago.setEditable(true);
            txtmonto.setEditable(true);      
   }
        public void limpiar(){
            txtdetalle.setText("");
            txtserie.setText("");
            txtnumero.setText("");
            txtcodigocolaborador.setText("");
            txtnombrecolaborador.setText("");
            txttipocambio.setText("");
            txtformapago.setText("");
            txtmonto.setText("");      
   }
    
}
