package view.alquiler;

import Modelo.Cliente;
import Modelo.Dao;
import Modelo.Departamento;
import Modelo.Pais;
import Modelo.Provincia;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import view.Login;


/**
 *
 * @author Dani
 */
public class nuevoCliente extends javax.swing.JFrame {

    /**
     * Creates new form nuevoUsuario
     */
    Dao dao=new Dao();
    boolean nuevo=false;
    Date fecha  =new Date();
    
    String resultado="",Activo="";
    	static Login is;

	String nombreUser = Login.txtusuario.getText();
        String ip;
    public nuevoCliente() {
        initComponents();
        
         this.setIconImage(new ImageIcon(getClass().getResource("/images/edit-copy.png")).getImage());

            try {
          ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(nuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

            this.setTitle("Registrar cliente. " + nombreUser+"@ServiciosGeneralesViviana " + "[{"+ ip +"}]" );
                darColor();

        Utilidades.generarIDCliente();
        
        txtfmodif.setText(Utilidades.formatDate(fecha));
        
     
        
       // txt.setText(Utilidades.formatDate(fecha));
        try {
            txtip.setText(InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName());
        } catch (UnknownHostException ex) {
            Logger.getLogger(nuevoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtuser1.setText(nombreUser);
        dao.listarPais(jcpais);
        txtndoc.grabFocus();
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtcontacto = new javax.swing.JTextField();
        txtcpostal = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbtipodoc = new javax.swing.JComboBox<>();
        txtdireccion = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtndoc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtip = new javax.swing.JTextField();
        txtuser1 = new javax.swing.JTextField();
        txtfmodif = new javax.swing.JTextField();
        txtnobra = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jcpais = new javax.swing.JComboBox<>();
        jcdepartamento = new javax.swing.JComboBox<>();
        jcprovincia = new javax.swing.JComboBox<>();
        jcdistrito = new javax.swing.JComboBox<>();
        txttelefono = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtobra = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        chactivo = new javax.swing.JCheckBox();
        txtobservaciones = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtcontacto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcontactoKeyTyped(evt);
            }
        });

        txtcpostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcpostalKeyTyped(evt);
            }
        });

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtemailKeyTyped(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/applications-system.png"))); // NOI18N
        jButton9.setText("Grabar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton9KeyTyped(evt);
            }
        });

        jLabel12.setText("Email");

        jLabel11.setText("Codigo postal");

        jLabel10.setText("Contacto");

        jLabel8.setText("Distrito");

        cbtipodoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L.E / DNI", "CARNET EXT", "RUC", "PASAPORTE PASAPORTE", "PART. NAC", "OTROS" }));
        cbtipodoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipodocActionPerformed(evt);
            }
        });
        cbtipodoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbtipodocFocusGained(evt);
            }
        });
        cbtipodoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbtipodocKeyTyped(evt);
            }
        });

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtndoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtndocActionPerformed(evt);
            }
        });
        txtndoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtndocKeyTyped(evt);
            }
        });

        jLabel1.setText("Tipo de documento");

        jLabel2.setText("N° Documento");

        jLabel3.setText("Nombre");

        jLabel4.setText("Direccion");

        jLabel5.setText("Pais");

        jLabel6.setText("Departamento");

        jLabel7.setText("Provincia");

        txtip.setEditable(false);

        txtuser1.setEditable(false);

        txtfmodif.setEditable(false);

        txtnobra.setText("0");
        txtnobra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnobraKeyTyped(evt);
            }
        });

        jLabel21.setText("N° de Obra");

        jLabel22.setText("Fecha Modificación");

        jLabel23.setText("User");

        jLabel24.setText("Ip");

        txtid.setEditable(false);

        jLabel19.setText("Id");

        jcpais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione" }));
        jcpais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcpaisMouseClicked(evt);
            }
        });
        jcpais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcpaisItemStateChanged(evt);
            }
        });
        jcpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcpaisActionPerformed(evt);
            }
        });
        jcpais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcpaisFocusGained(evt);
            }
        });
        jcpais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcpaisKeyTyped(evt);
            }
        });

        jcdepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcdepartamentoItemStateChanged(evt);
            }
        });
        jcdepartamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcdepartamentoFocusGained(evt);
            }
        });
        jcdepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcdepartamentoKeyTyped(evt);
            }
        });

        jcprovincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcprovinciaItemStateChanged(evt);
            }
        });
        jcprovincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcprovinciaActionPerformed(evt);
            }
        });
        jcprovincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcprovinciaFocusGained(evt);
            }
        });
        jcprovincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcprovinciaKeyTyped(evt);
            }
        });

        jcdistrito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcdistritoItemStateChanged(evt);
            }
        });
        jcdistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcdistritoActionPerformed(evt);
            }
        });
        jcdistrito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcdistritoFocusGained(evt);
            }
        });
        jcdistrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcdistritoKeyTyped(evt);
            }
        });

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        jLabel25.setText("Telefono");

        txtobra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtobraKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtobraKeyReleased(evt);
            }
        });

        jLabel26.setText("Obra");

        chactivo.setSelected(true);
        chactivo.setText("Activo");

        txtobservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtobservacionesActionPerformed(evt);
            }
        });
        txtobservaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtobservacionesKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtobservacionesKeyTyped(evt);
            }
        });

        jLabel9.setText("Observación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtndoc)
                                .addComponent(txtnombre)
                                .addComponent(txtdireccion)
                                .addComponent(cbtipodoc, 0, 355, Short.MAX_VALUE)
                                .addComponent(jcpais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcdepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcprovincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel22)
                                .addComponent(jLabel24)
                                .addComponent(jLabel23))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtfmodif)
                                        .addComponent(txtuser1)
                                        .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(txtobservaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE))))))
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel21)
                    .addComponent(jLabel8)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txttelefono)
                        .addComponent(txtcontacto)
                        .addComponent(txtcpostal, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtemail)
                        .addComponent(txtobra, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtnobra, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jcdistrito, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                    .addComponent(chactivo))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jcdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbtipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtndoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jcprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtcontacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtcpostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chactivo)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtobservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtfmodif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtuser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcdistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcdistritoActionPerformed

    }//GEN-LAST:event_jcdistritoActionPerformed

    private void jcdistritoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcdistritoItemStateChanged

    }//GEN-LAST:event_jcdistritoItemStateChanged

    private void jcprovinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcprovinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcprovinciaActionPerformed

    private void jcprovinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcprovinciaItemStateChanged
        Provincia provincia = (Provincia) this.jcprovincia.getSelectedItem();
        int id = provincia.getIdProvincia();
        System.out.println(id);
        dao.listarDistrito(jcdistrito, id);
    }//GEN-LAST:event_jcprovinciaItemStateChanged

    private void jcdepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcdepartamentoItemStateChanged
        Departamento departamento = (Departamento) this.jcdepartamento.getSelectedItem();
        int id = departamento.getIdDepartamento();
        dao.listarProvincia(jcprovincia, id);
    }//GEN-LAST:event_jcdepartamentoItemStateChanged

    private void jcpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcpaisActionPerformed

    private void jcpaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcpaisItemStateChanged

        Pais pais = (Pais) this.jcpais.getSelectedItem();
        int id = pais.getIdPais();
        //de.listar_provincia(jcdepartamento, id);
        dao.listarDepartamento(jcdepartamento, id);
    }//GEN-LAST:event_jcpaisItemStateChanged

    private void jcpaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcpaisMouseClicked

    }//GEN-LAST:event_jcpaisMouseClicked

    private void cbtipodocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipodocActionPerformed
        //        Rol r = (Rol) jComboBox1.getSelectedItem();
        //		     String id = r.getIdrol();
        //                     dao.listarRol(jComboBox1, id);
    }//GEN-LAST:event_cbtipodocActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       
        nuevo = true;
        
        if (txtndoc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar N° de documento");
           txtndoc.grabFocus();
            return;
        }
        
         if (txtnombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un nombre");
           txtndoc.grabFocus();
            return;
        }
         
          if (txtdireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar una dirección");
           txtdireccion.grabFocus();
            return;
        }
        
        
        
        Cliente cl=new Cliente();
 
        cl.setCodigo(txtid.getText());
          String valortd = cbtipodoc.getSelectedItem().toString();
        cl.setTipodoc(valortd);
        cl.setNdoc(txtndoc.getText());
        cl.setNombre(txtnombre.getText());
        cl.setTelefono(txttelefono.getText());
        cl.setContacto(txtcontacto.getText());
        cl.setCodigopostal(txtcpostal.getText());
        cl.setDireccion(txtdireccion.getText());
        
        String valor1 = jcpais.getSelectedItem().toString();
        cl.setPais(valor1);
        String valor2 = jcdepartamento.getSelectedItem().toString();
        cl.setDepartamento(valor2);
        String valor3 = jcprovincia.getSelectedItem().toString();
        cl.setProvincia(valor3);
	String valor4 = jcdistrito.getSelectedItem().toString();
        cl.setDistrito(valor4);
        
        cl.setObra(txtobra.getText());
        cl.setNunobra(Integer.parseInt(txtnobra.getText()));
        cl.setObservaciones(txtobservaciones.getText());
        cl.setNomusum(txtuser1.getText());
        cl.setFecham(txtfmodif.getText());
        cl.setIp(txtip.getText());
        cl.setEmail(txtemail.getText());
 
        

        String activo;
        if(chactivo.isSelected())
        {
            activo = "1";
        }else
        {
            activo = "0";
        }

        cl.setActivo(activo);
       

        if (nuevo) {
            resultado = dao.GuardarCliente(cl);
            JOptionPane.showMessageDialog(rootPane, resultado);
            dao.mostrarClientes("","","","","");
            RegistClientes.tableClientes.setRowSelectionInterval(0, 0);

        }
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
      
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
     
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        String cadena= (txtemail.getText()).toUpperCase();
 txtemail.setText(cadena);
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtobservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtobservacionesActionPerformed
        
    }//GEN-LAST:event_txtobservacionesActionPerformed

    private void txtndocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtndocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtndocActionPerformed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        String cadena= (txtnombre.getText()).toUpperCase();
 txtnombre.setText(cadena);
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
  String cadena= (txtdireccion.getText()).toUpperCase();
 txtdireccion.setText(cadena);
 // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void txtobservacionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobservacionesKeyReleased
      String cadena= (txtobservaciones.getText()).toUpperCase();
 txtobservaciones.setText(cadena);
    }//GEN-LAST:event_txtobservacionesKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        String cadena= (txtobservaciones.getText()).toUpperCase();
 txtobservaciones.setText(cadena);
    }//GEN-LAST:event_txtemailKeyReleased

    private void txtobraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobraKeyReleased
      String cadena= (txtobservaciones.getText()).toUpperCase();
 txtobservaciones.setText(cadena);
    }//GEN-LAST:event_txtobraKeyReleased

    private void cbtipodocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbtipodocKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtndoc.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipodocKeyTyped

    private void txtndocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtndocKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtnombre.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtndocKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtdireccion.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jcpais.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void jcpaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcpaisKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jcdepartamento.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jcpaisKeyTyped

    private void jcdepartamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcdepartamentoKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
               jcprovincia.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jcdepartamentoKeyTyped

    private void jcprovinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcprovinciaKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtobservaciones.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jcprovinciaKeyTyped

    private void txtobservacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobservacionesKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jcdistrito.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtobservacionesKeyTyped

    private void jcdistritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcdistritoKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txttelefono.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jcdistritoKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtcontacto.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtcontactoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactoKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtcpostal.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactoKeyTyped

    private void txtcpostalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcpostalKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtemail.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtcpostalKeyTyped

    private void txtemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtobra.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyTyped

    private void txtobraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtobraKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtnobra.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtobraKeyTyped

    private void txtnobraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnobraKeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jButton9.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtnobraKeyTyped

    private void jButton9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton9KeyTyped
char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jButton9.doClick();
            }
        
        cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
        
                // TODO add your handling code here:
    }//GEN-LAST:event_jButton9KeyTyped

    private void cbtipodocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbtipodocFocusGained
cbtipodoc.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_cbtipodocFocusGained

    private void jcdistritoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcdistritoFocusGained
jcdistrito.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_jcdistritoFocusGained

    private void jcpaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcpaisFocusGained
     jcpais.showPopup();   // TODO add your handling code here:
    }//GEN-LAST:event_jcpaisFocusGained

    private void jcdepartamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcdepartamentoFocusGained
       jcdepartamento.showPopup(); // TODO add your handling code here:
    }//GEN-LAST:event_jcdepartamentoFocusGained

    private void jcprovinciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcprovinciaFocusGained
jcprovincia.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_jcprovinciaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cbtipodoc;
    private javax.swing.JCheckBox chactivo;
    public static javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JComboBox<String> jcdepartamento;
    public static javax.swing.JComboBox<String> jcdistrito;
    public static javax.swing.JComboBox<String> jcpais;
    public static javax.swing.JComboBox<String> jcprovincia;
    public static javax.swing.JTextField txtcontacto;
    public static javax.swing.JTextField txtcpostal;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtemail;
    public static javax.swing.JTextField txtfmodif;
    public static javax.swing.JTextField txtid;
    public static javax.swing.JTextField txtip;
    public static javax.swing.JTextField txtndoc;
    public static javax.swing.JTextField txtnobra;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtobra;
    public static javax.swing.JTextField txtobservaciones;
    public static javax.swing.JTextField txttelefono;
    public static javax.swing.JTextField txtuser1;
    // End of variables declaration//GEN-END:variables
// public void obtenerFecha1() {
//        String rx1 = Utilidades.formatDate(datefn.getDate());
//        txtfechanacimiento.setText(rx1);
//    }
//  public void obtenerFecha2() {
//        String rx2 = Utilidades.formatDate(datefi.getDate());
//        txtfechaingreso.setText(rx2);
//    }
//   public void obtenerFecha3() {
//        String rx3 = Utilidades.formatDate(dateft.getDate());
//        txtfechasalida.setText(rx3);
//    }
    
    public void darColor(){
        
txtndoc.setBackground(new Color(255,255,153));
  txtnombre.setBackground(new Color(255,255,153));
    txttelefono.setBackground(new Color(255,255,153));
    txtcontacto.setBackground(new Color(255,255,153));
        txtcpostal.setBackground(new Color(255,255,153));
     txtdireccion.setBackground(new Color(255,255,153));
        cbtipodoc.setBackground(new Color(255,255,153));
        jcpais.setBackground(new Color(255,255,153));
        jcdepartamento.setBackground(new Color(255,255,153));
        jcprovincia.setBackground(new Color(255,255,153));
	jcdistrito.setBackground(new Color(255,255,153));
        
   txtobra.setBackground(new Color(255,255,153));
      txtnobra.setBackground(new Color(255,255,153));
     txtobservaciones.setBackground(new Color(255,255,153));
   
   txtemail.setBackground(new Color(255,255,153));
    }
}
