/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.alquiler;

import Modelo.Dao;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.table.DefaultTableCellRenderer;

import swing.xp.shapeTabbedPaneUI;
import view.Login;
import view.entradasalidas.User;

/**
 *
 * @author Dani
 */
public class RegistAlquiler extends javax.swing.JFrame {

    Dao dao = new Dao();

    static Login is;
    String ip;
    String nombreUser = Login.txtusuario.getText();

    public RegistAlquiler() {
        initComponents();

        int j = 1;

        ptable();
        menubar();
        tabbedpanel();

        this.setIconImage(new ImageIcon(getClass().getResource("/images/folder-saved-search.png")).getImage());

        try {
            ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(RegistAlquiler.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setTitle("Registro de Alquiler de Vehiculos.  " + nombreUser + "@ServiciosGeneralesViviana " + "[{" + ip + "}]");
        
        dao.mostrarAlquiler("", "", "", "", "", "", "", "");
        
        if (RegistAlquiler.tableAlquiler.getRowCount() != 0) {
            tableAlquiler.setRowSelectionInterval(0, 0);
            cantidadRegist(j);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btndouwn = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAlquiler = new javax.swing.JTable();
        cantidad = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton8.setBackground(new java.awt.Color(184, 221, 182));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brain_2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-copy.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-search_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar_16x16.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btndouwn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-down_1.png"))); // NOI18N
        btndouwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndouwnActionPerformed(evt);
            }
        });

        btnup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-up.png"))); // NOI18N
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-log-out.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-refresh.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndouwn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btndouwn)
                    .addComponent(btnup)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        tableAlquiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableAlquiler.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableAlquiler.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tableAlquiler.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableAlquiler.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAlquilerMouseClicked(evt);
            }
        });
        tableAlquiler.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableAlquilerKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableAlquiler);

        jTabbedPane1.addTab("Registro de alquiler", jScrollPane1);

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 51, 255));
        cantidad.setText("jLabel1");

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("SAFV - SISTEMA DE ADMINISTRACIÓN DE FLOTA VEHICULAR - SERVICIOS GENERALES VIVIANA EIRL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(cantidad))
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setPreferredSize(new java.awt.Dimension(324, 29));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem2.setText("Ver");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Herramientas");
        jMenu5.add(jSeparator2);

        jMenuItem3.setText("Menu principal");
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator4);

        jMenuItem4.setText("Submenu");
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        jMenu9.setText("Sistemas");

        jMenuItem5.setText("Procesos");
        jMenu9.add(jMenuItem5);

        jMenuBar1.add(jMenu9);

        jMenu11.setText("Reportes");

        jMenuItem6.setText("Imprimir");
        jMenu11.add(jMenuItem6);

        jMenuBar1.add(jMenu11);

        jMenu14.setText("Ayuda");

        jMenuItem7.setText("?");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem7);

        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void tableAlquilerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAlquilerMouseClicked
    }//GEN-LAST:event_tableAlquilerMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int fila = tableAlquiler.getSelectedRow();
        String activo = "";
        if (fila < 0) {
            JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");

        } else {

            Date fecha1 = null, fecha2 = null;
            // int fila = tableUsuarios.getSelectedRow();
            ActualizarAlquiler aa = new ActualizarAlquiler();
            aa.setVisible(true);
            aa.setLocationRelativeTo(null);

            ActualizarAlquiler.txtcodigo.setText(tableAlquiler.getValueAt(fila, 0).toString());
            ActualizarAlquiler.txtidcliente.setText(tableAlquiler.getValueAt(fila, 1).toString());
            ActualizarAlquiler.txtndoc.setText(tableAlquiler.getValueAt(fila, 3).toString());

            ActualizarAlquiler.txtnombre.setText(tableAlquiler.getValueAt(fila, 2).toString());
            ActualizarAlquiler.txttelefono.setText(tableAlquiler.getValueAt(fila, 4).toString());

            ActualizarAlquiler.txtobra.setText(tableAlquiler.getValueAt(fila, 5).toString());
            ActualizarAlquiler.txtnobra.setText(tableAlquiler.getValueAt(fila, 6).toString());
            ActualizarAlquiler.txtidvehiculo.setText(tableAlquiler.getValueAt(fila, 7).toString());
            ActualizarAlquiler.txttipoveh.setText(tableAlquiler.getValueAt(fila, 8).toString());
            ActualizarAlquiler.txtmatricula.setText(tableAlquiler.getValueAt(fila, 9).toString());
            ActualizarAlquiler.txtplaca.setText(tableAlquiler.getValueAt(fila, 10).toString());
            ActualizarAlquiler.txtmarca.setText(tableAlquiler.getValueAt(fila, 11).toString());
            ActualizarAlquiler.txtpotencia.setText(tableAlquiler.getValueAt(fila, 12).toString());
            ActualizarAlquiler.txtcosto.setText(tableAlquiler.getValueAt(fila, 13).toString());

            try {
                fecha1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) tableAlquiler.getValueAt(fila, 14).toString());
            } catch (ParseException ex) {
                Logger.getLogger(RegistAlquiler.class.getName()).log(Level.SEVERE, null, ex);
            }

            ActualizarAlquiler.dateAlq.setDate(fecha1);

            ActualizarAlquiler.txthora.setText(tableAlquiler.getValueAt(fila, 15).toString());

            try {
                fecha2 = new SimpleDateFormat("yyyy-MM-dd").parse((String) tableAlquiler.getValueAt(fila, 16).toString());

            } catch (ParseException ex) {
                Logger.getLogger(RegistAlquiler.class.getName()).log(Level.SEVERE, null, ex);
            }

            ActualizarAlquiler.datefr.setDate(fecha2);

            ActualizarAlquiler.txtunidades.setText(tableAlquiler.getValueAt(fila, 17).toString());
            ActualizarAlquiler.txtprecio.setText(tableAlquiler.getValueAt(fila, 18).toString());
            ActualizarAlquiler.txttotal.setText(tableAlquiler.getValueAt(fila, 19).toString());
            ActualizarAlquiler.txtdiasres.setText(tableAlquiler.getValueAt(fila, 20).toString());
            ActualizarAlquiler.txttotaldias.setText(tableAlquiler.getValueAt(fila, 21).toString());

            ActualizarAlquiler.txtobservacion.setText(tableAlquiler.getValueAt(fila, 22).toString());
            ActualizarAlquiler.txtfechact.setText(tableAlquiler.getValueAt(fila, 23).toString());
            ActualizarAlquiler.txtuser.setText(tableAlquiler.getValueAt(fila, 24).toString());
            ActualizarAlquiler.txtip.setText(tableAlquiler.getValueAt(fila, 25).toString());

            ActualizarAlquiler.jButton10.grabFocus();

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NuevoAlquiler nal = new NuevoAlquiler();
        nal.setVisible(true);
        nal.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SearchAlquiler salq = new SearchAlquiler();
        salq.setVisible(true);
        salq.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        dao.mostrarAlquiler("", "", "", "", "", "", "", "");
        tableAlquiler.setRowSelectionInterval(0, 0);


    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        up();
    }//GEN-LAST:event_btnupActionPerformed

    private void btndouwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndouwnActionPerformed
        down();
    }//GEN-LAST:event_btndouwnActionPerformed

    private void tableAlquilerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableAlquilerKeyReleased
        /*if((evt.getKeyCode()==KeyEvent.VK_DOWN) || (evt.getKeyCode()==KeyEvent.VK_UP) ){
           tableUsuarios.getSelectedRow();
           
       }*/

    }//GEN-LAST:event_tableAlquilerKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        _rRegistAlquiler _rregistalquiler = new _rRegistAlquiler();
        _rregistalquiler.setVisible(true);
        _rregistalquiler.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        User userxy = new User();
        userxy.setVisible(true);
        userxy.setLocationRelativeTo(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistAlquiler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistAlquiler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btndouwn;
    public static javax.swing.JButton btnup;
    public static javax.swing.JLabel cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable tableAlquiler;
    // End of variables declaration//GEN-END:variables
      public void menubar() {

        jMenuBar1.setUI(new BasicMenuBarUI() {
            public void paint(Graphics g, JComponent c) {
                g.setColor(new Color(184, 221, 182));

                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });
    }

    public void tabbedpanel() {

        JLabel lab = new JLabel("Registro de Alquiler");
        lab.setPreferredSize(new Dimension(140, 35));
        jTabbedPane1.setTabComponentAt(0, lab);

        jTabbedPane1.setUI(new shapeTabbedPaneUI());

    }

    public void ptable() {

        tableAlquiler.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void up() {
        int index = 0;
        index = tableAlquiler.getSelectedRow();
        //System.out.println("up= " + index);

        if (index > 0) {
            tableAlquiler.setRowSelectionInterval(index - 1, index - 1);
            btndouwn.setEnabled(true);
            cantidadRegist(index);

        } else {
            btnup.setEnabled(false);
            btndouwn.setEnabled(true);
        }

    }

    public void down() {
        int index;

        index = tableAlquiler.getSelectedRow();

        if (tableAlquiler.getRowCount() > (index + 1)) {
            tableAlquiler.setRowSelectionInterval(index + 1, index + 1);

            cantidadRegist(index + 2);
            btnup.setEnabled(true);
        } else {
            btndouwn.setEnabled(false);
            btnup.setEnabled(true);

        }
    }

    public void cantidadRegist(int j) {
        int fila = tableAlquiler.getSelectedRow();
        int x = 0;
        for (int i = 0; i < tableAlquiler.getRowCount(); i++) {
            x++;
        }

        cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
    }

}
