/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.usuario;

import Modelo.Dao;
import Modelo.Usuarios;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static view.usuario.RegisUsuarios.tableUsuarios;

/**
 *
 * @author Dani
 */
public class Completar extends javax.swing.JFrame {

    /**
     * Creates new form completar
     */
    boolean actualizar=false;
    String resultado="",valor="";
    Dao dao=new Dao();
    Date fecha=new Date();
    public Completar() {
        initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/images/document-save-as.png")).getImage());

        txtff.setText(Utilidades.formatDate(fecha));
           txtff.setDisabledTextColor(Color.blue);
           
//           cba.grabFocus();
            
                 jButton1.grabFocus();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cba = new javax.swing.JComboBox<>();
        txtff = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Acción en el Documento ");

        cba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actualizar", "Guardar" }));
        cba.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbaFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbaFocusGained(evt);
            }
        });
        cba.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbaKeyTyped(evt);
            }
        });

        txtff.setBackground(new java.awt.Color(255, 255, 204));
        txtff.setForeground(new java.awt.Color(0, 0, 255));
        txtff.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtff.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Check_16x16.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete_16x16.png"))); // NOI18N
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Genera los documentos y realiza transacciones*");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/applications-system_1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cba, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtff, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        if(cba.getSelectedItem().equals("Actualizar")) {
                enableTrue();
		dispose();
                Actualizar.txtcontraseña.grabFocus();
	}

						
						if(cba.getSelectedItem().equals("Guardar")) {
							actualizar=true;
                                                        
          if (Actualizar.txtnombres.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el nombre del usuario");
            Actualizar.txtnombreUsuario.grabFocus();
            return;
        }
        
              if (Actualizar.txtnd.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el documento de identidad");
            Actualizar.txtnd.grabFocus();
            return;
        }
                                                            Usuarios u=new Usuarios();

							
							u.setUsername(Actualizar.txtnombreUsuario.getText());
							// String userr="x3";
							// u.setUsername(userr);

							u.setPassword(Actualizar.txtcontraseña.getText());
							// String ps="123";
							// u.setPassword(ps);
							// System.out.println(txtcontraseña.getText());

							u.setNumdoc(Actualizar.txtnd.getText());
							// String doc="dni";
							// u.setNumdoc(doc);
							// System.out.println(txtdoc.getText());

							u.setIde(Actualizar.txtide.getText());
						
							// String m="mtt";
							// u.setMaterno(m);
							// System.out.println(txtmaterno.getText());

							u.setNombres(Actualizar.txtnombres.getText());
							// String noms="nombre";
							// u.setNombres(noms);
							// System.out.println(txtnombres.getText());

							u.setEmail(Actualizar.txtemail.getText());
							// String em="email";
							// u.setEmail(em);
							// System.out.println(txtemail.getText());
							String Activo;
							if (Actualizar.ckactivo.isSelected()) {
								Activo = "1";
							} else {
								Activo = "0";
							}
							
							u.setEsactivo(Activo);
							// System.out.println(EsAdmin);
							String EsAdmin;
							if (Actualizar.ckadmin.isSelected()) {
								EsAdmin = "1";
							} else {
								EsAdmin = "0";
							}

							u.setEsadmin(EsAdmin);
							
							
							
							valor=Actualizar.cbrol.getSelectedItem().toString();
							u.setRol(dao.verificarRol(valor));
							
						
							/* ======================================================= */

							 u.setFechac(Actualizar.txtfechactual.getText());
							//String f = "07/03/2019";
							//u.setFechac(f);
							// System.out.println(txtfechaActual.getText());

							u.setFecham(Actualizar.txtfecha.getText());
							// String f1="07/03/2018";
							// u.setFecham(f1);
							// System.out.println(txtfecha.getText());

							u.setNomusum(Actualizar.txtuser.getText());
							// String usu7="usuar";
							// u.setNomusum(usu7);
							// System.out.println(txtuser.getText());

							u.setIp(Actualizar.txtip.getText());
							// String ux="192.168.2.33 - Equipo-Dani";
							// u.setIp(ux);
							// System.out.println(txtip.getText());
							
							if(actualizar){
								resultado=dao.ModificarUsuario(u);
								JOptionPane.showMessageDialog(rootPane, resultado);
								enableFalse();
                                                                dao.mostrarUsuarios("","","","");
                                                                tableUsuarios.setRowSelectionInterval(0, 0);
							}
							dispose();
							
                                                }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
   
 
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       	  dispose();								
          enableFalse();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbaKeyTyped
          char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                 jButton1.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_cbaKeyTyped

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                 jButton1.doClick();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_jButton1KeyTyped

    private void cbaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbaFocusGained

        // TODO add your handling code here:
    }//GEN-LAST:event_cbaFocusGained

    private void cbaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbaFocusLost
    }//GEN-LAST:event_cbaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Completar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Completar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Completar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Completar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Completar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cba;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtff;
    // End of variables declaration//GEN-END:variables
public void enableTrue() {

		Actualizar.txtcontraseña.setEditable(true);
		Actualizar.txtnd.setEditable(true);
//		Actualizar.txtide.setEditable(true);
		Actualizar.txtnombres.setEditable(true);
		Actualizar.txtemail.setEditable(true);
		Actualizar.ckactivo.setEnabled(true);
		Actualizar.ckadmin.setEnabled(true);
		Actualizar.cbrol.setEnabled(true);

                Actualizar.txtcontraseña.setBackground(new Color(255,255,153)); 
                Actualizar.txtnd.setBackground(new Color(255,255,153)); 
                Actualizar.txtide.setBackground(new Color(255,255,153)); 
		Actualizar.txtnombres.setBackground(new Color(255,255,153)); 
		Actualizar.txtemail.setBackground(new Color(255,255,153)); 
		Actualizar.cbrol.setBackground(new Color(255,255,153)); 
                
	}
	public void enableFalse() {

                Actualizar.txtnd.setEditable(false);
		Actualizar.txtcontraseña.setEditable(false);
//		Actualizar.txtide.setEditable(false);
		Actualizar.txtnombres.setEditable(false);
		Actualizar.txtemail.setEditable(false);
                Actualizar.ckactivo.setEnabled(false);
		Actualizar.ckadmin.setEnabled(false);
		Actualizar.cbrol.setEnabled(false);
                
                Actualizar.txtnd.setBackground(new Color(255,255,255)); 
                Actualizar.txtcontraseña.setBackground(new Color(255,255,255)); 
		Actualizar.txtide.setBackground(new Color(255,255,255)); 
		Actualizar.txtnombres.setBackground(new Color(255,255,255)); 
		Actualizar.txtemail.setBackground(new Color(255,255,255)); 
		Actualizar.cbrol.setBackground(new Color(255,255,255)); 
	}
        
        
	
}
