/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.checkList;

import Modelo.Dao;
import Modelo.rDetalleVehiculo;
import Modelo.rOrden;
import Modelo.rpuser;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.table.DefaultTableCellRenderer;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;
import swing.xp.shapeTabbedPaneUI;
import view.Login;
import view.entradasalidas.User;
import static view.vehicular.RegisVehiculos.tabledetalle;
import static view.vehicular.RegisVehiculos.tablevehiculos;

/**
 *
 * @author Dani
 */
public class InspeccionMovil extends javax.swing.JFrame {

    Dao dao = new Dao();
    int indice;
    Date fecha = new Date();
    static Login is;
    String ip;
    String nombreUser = Login.txtusuario.getText();

    public InspeccionMovil() {
        initComponents();
        ptable();
        ptable2();
        menubar();
        tabbedpanel();

        this.setIconImage(new ImageIcon(getClass().getResource("/images/folder-saved-search.png")).getImage());

        try {
            ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(InspeccionMovil.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setTitle("Registro de Inspección Movil.  " + nombreUser + "@ServiciosGeneralesViviana " + "[{" + ip + "}]");

        dao.mostrarChecklist("", "");
        dao.MOSTRARORDEN("", "");

        indice = 0;
        if(InspeccionMovil.tableinspeccion.getRowCount()!=0){
            tableinspeccion.setRowSelectionInterval(0, 0);
            verFilaSeleccionada();
        }
//       btnverfila.setEnabled(false);
        int j = 1;
        cantidadRegist(j);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        btnverfila = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        btndouwn = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableinspeccion = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableorden = new javax.swing.JTable();
        cantidad = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-search.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        btnverfila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-copy.png"))); // NOI18N
        btnverfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverfilaActionPerformed(evt);
            }
        });

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/printer.png"))); // NOI18N
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-log-out.png"))); // NOI18N
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-refresh.png"))); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        btndouwn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-down_1.png"))); // NOI18N
        btndouwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndouwnActionPerformed(evt);
            }
        });

        btnup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-up.png"))); // NOI18N
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnverfila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndouwn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btndouwn)
                        .addComponent(btnup))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10)
                        .addComponent(btnverfila)
                        .addComponent(jButton14)
                        .addComponent(jButton15)
                        .addComponent(jButton16)))
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 51, 102));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        tableinspeccion.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tableinspeccion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableinspeccion.setSelectionBackground(java.awt.Color.yellow);
        tableinspeccion.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableinspeccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableinspeccionMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableinspeccion);

        jTabbedPane1.addTab("Registro Inspección Movil", jScrollPane2);

        tableorden.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tableorden.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableorden.setSelectionBackground(java.awt.Color.yellow);
        tableorden.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(tableorden);

        jTabbedPane1.addTab("Detalle de Inspección", jScrollPane3);

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 51, 255));
        cantidad.setText("jLabel1");

        jButton8.setBackground(new java.awt.Color(184, 221, 182));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brain_2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("SAFV - SISTEMA DE ADMINISTRACIÓN DE FLOTA VEHICULAR - SERVICIOS GENERALES VIVIANA EIRL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(cantidad))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(184, 221, 182));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(324, 29));

        jMenu1.setBackground(new java.awt.Color(184, 221, 182));
        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem2.setText("Ver");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Herramientas");
        jMenu5.add(jSeparator2);

        jMenuItem3.setText("Menu principal");
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator4);

        jMenuItem4.setText("Submenu");
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        jMenu9.setText("Sistemas");

        jMenuItem5.setText("Procesos");
        jMenu9.add(jMenuItem5);

        jMenuBar1.add(jMenu9);

        jMenu11.setText("Reportes");

        jMenuItem6.setText("Imprimir");
        jMenu11.add(jMenuItem6);

        jMenuBar1.add(jMenu11);

        jMenu14.setText("Ayuda");

        jMenuItem7.setText("?");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem7);

        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (indice == 0) {
            SearchInspeccion sinspeccion = new SearchInspeccion();
            sinspeccion.setVisible(true);
            sinspeccion.setLocationRelativeTo(null);
        }
        if (indice == 1) {
            SearchOrden so = new SearchOrden();
            so.setVisible(true);
            so.setLocationRelativeTo(null);
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnverfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverfilaActionPerformed
        CheckList checklist22 = new CheckList();
        checklist22.setLocationRelativeTo(null);
        checklist22.setVisible(true);
//        int filaD = tableDetallecaja.getSelectedRow();
//        String tarprop = "";
//
//        if(filaD<0){
//            JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");
//
//        }else{
//
//            ActDetalleCaja dvhx= new   ActDetalleCaja();
//            dvhx.setVisible(true);
//            dvhx.setLocationRelativeTo(null);
//
//            ActDetalleCaja.IDDETALLE.setText(tableDetallecaja.getValueAt(filaD, 0).toString());
//            ActDetalleCaja.txtcodigo.setText(tableDetallecaja.getValueAt(filaD, 1).toString());
//            ActDetalleCaja.lblusuario.setText(tableDetallecaja.getValueAt(filaD, 2).toString());
//            ActDetalleCaja.lblfecha.setText(tableDetallecaja.getValueAt(filaD, 3).toString());
//            ActDetalleCaja.lbldia.setText(tableDetallecaja.getValueAt(filaD, 4).toString());
//
//            String concepto = (String) tableDetallecaja.getValueAt(filaD, 5).toString();
//            ActDetalleCaja.cbconcepto.getModel().setSelectedItem(concepto);
//
//            ActDetalleCaja.txtclave.setText(tableDetallecaja.getValueAt(filaD, 6).toString());
//            ActDetalleCaja.txtvalor.setText(tableDetallecaja.getValueAt(filaD, 7).toString());
//
//            String documento = (String) tableDetallecaja.getValueAt(filaD, 8).toString();
//            ActDetalleCaja.cbdocumento.getModel().setSelectedItem(documento);
//
//            ActDetalleCaja.txtserie.setText(tableDetallecaja.getValueAt(filaD, 9).toString());
//            ActDetalleCaja.txtnumero.setText(tableDetallecaja.getValueAt(filaD, 10).toString());
//
//            String act = (String) tableDetallecaja.getValueAt(filaD, 11).toString();
//            ActDetalleCaja.cbtipoactividad.getModel().setSelectedItem(act);
//
//            String monto = (String) tableDetallecaja.getValueAt(filaD, 12).toString();
//            ActDetalleCaja.cbmonto.getModel().setSelectedItem(monto);
//
//            ActDetalleCaja.txtsaldo.setText(tableDetallecaja.getValueAt(filaD, 13).toString());
//            ActDetalleCaja.txttipocam.setText(tableDetallecaja.getValueAt(filaD, 14).toString());
//            ActDetalleCaja.txtobservacion.setText(tableDetallecaja.getValueAt(filaD, 15).toString());
//            ActDetalleCaja.txtfecha.setText(tableDetallecaja.getValueAt(filaD, 16).toString());
//            ActDetalleCaja.txtuser.setText(tableDetallecaja.getValueAt(filaD, 17).toString());
//            ActDetalleCaja.txtip.setText(tableDetallecaja.getValueAt(filaD, 18).toString());
//
//            String codigov=txtcodigo.getText();
//            String fechav=lblfecha.getText();
//
//            dao.mostrarDetalleCaja2(codigov, fechav);
//            totales();
//
//        }

    }//GEN-LAST:event_btnverfilaActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
//        if(indice==0){
        reporte reporte80 = new reporte();
        reporte80.setVisible(true);
        reporte80.setLocationRelativeTo(null);
//        }else{
//            reporteorden();
//        }
        //reporteDetalleCaja();
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        if (indice == 0) {

            dao.mostrarChecklist("", "");
            tableinspeccion.setRowSelectionInterval(0, 0);

        }

        if (indice == 1) {
            int verfilay = tableinspeccion.getSelectedRow();
            String idy = (String) tableinspeccion.getValueAt(verfilay, 0);
            dao.MOSTRARORDEN(idy, "");

            tableorden.setRowSelectionInterval(0, 0);

        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void btndouwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndouwnActionPerformed
        if (indice == 0) {
            down();

        }

        if (indice == 1) {
            down1();
        }

    }//GEN-LAST:event_btndouwnActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        if (indice == 0) {
            up();

        }

        if (indice == 1) {
            up1();
        }

    }//GEN-LAST:event_btnupActionPerformed

    private void tableinspeccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableinspeccionMouseClicked
        verFilaSeleccionada();
    }//GEN-LAST:event_tableinspeccionMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        jTabbedPane1.getSelectedIndex();
        indice = jTabbedPane1.getSelectedIndex();
        int j = 1;

        if (indice == 0) {
            if(InspeccionMovil.tableinspeccion.getRowCount()!=0){
//            dao.mostrarChecklist("", "");
//            tableinspeccion.setRowSelectionInterval(0, 0);
//            btnverfila.setEnabled(false);
            cantidadRegist(j);
            }
        }

        if (indice == 1) {
            if(InspeccionMovil.tableorden.getRowCount()!=0){
//            btnverfila.setEnabled(true);
            tableorden.setRowSelectionInterval(0, 0);
            cantidadRegist(j);
            }

        }

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        User userxy = new User();
        userxy.setVisible(true);
        userxy.setLocationRelativeTo(null);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InspeccionMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InspeccionMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InspeccionMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InspeccionMovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InspeccionMovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btndouwn;
    public static javax.swing.JButton btnup;
    private javax.swing.JButton btnverfila;
    public static javax.swing.JLabel cantidad;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable tableinspeccion;
    public static javax.swing.JTable tableorden;
    // End of variables declaration//GEN-END:variables
 public void verFilaSeleccionada() {
        int verfilax = tableinspeccion.getSelectedRow();

//        
        String id = (String) tableinspeccion.getValueAt(verfilax, 0);
//         String f = (String) tableinspeccion.getValueAt(verfilax, 2);

        dao.MOSTRARORDEN(id, "");
    }

    public void cantidadRegist(int j) {
        if (indice == 0) {
            int x = 0;
            for (int i = 0; i < tableinspeccion.getRowCount(); i++) {
                x++;
            }
            cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
        }

        if (indice == 1) {
            int x = 0;
            for (int i = 0; i < tableorden.getRowCount(); i++) {
                x++;
            }
            cantidad.setText("[" + j + "/" + String.valueOf(x) + "]");
        }
    }

    public void up() {
        int index = 0;
        index = tableinspeccion.getSelectedRow();

        if (index > 0) {
            tableinspeccion.setRowSelectionInterval(index - 1, index - 1);
            btndouwn.setEnabled(true);
            cantidadRegist(index);

        } else {
            btnup.setEnabled(false);
            btndouwn.setEnabled(true);
        }
        verFilaSeleccionada();
    }

    public void up1() {
        int index = 0;
        index = tableorden.getSelectedRow();

        if (index > 0) {
            tableorden.setRowSelectionInterval(index - 1, index - 1);
            btndouwn.setEnabled(true);
            cantidadRegist(index);

        } else {
            btnup.setEnabled(false);
            btndouwn.setEnabled(true);
        }
    }

    public void down() {
        int index;

        index = tableinspeccion.getSelectedRow();

        if (tableinspeccion.getRowCount() > (index + 1)) {
            tableinspeccion.setRowSelectionInterval(index + 1, index + 1);
            cantidadRegist(index + 2);
            btnup.setEnabled(true);
        } else {
            btndouwn.setEnabled(false);
            btnup.setEnabled(true);

        }
        verFilaSeleccionada();
    }

    public void down1() {
        int index;
        index = tableorden.getSelectedRow();

        if (tableorden.getRowCount() > (index + 1)) {
            tableorden.setRowSelectionInterval(index + 1, index + 1);
            cantidadRegist(index + 2);
            btnup.setEnabled(true);
        } else {
            btndouwn.setEnabled(false);
            btnup.setEnabled(true);
        }
    }

    public void ptable() {

        tableinspeccion.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void ptable2() {

        tableorden.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                l.setBorder(new LineBorder(new Color(239, 242, 210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                l.setBackground(new Color(184, 221, 182));

                l.setHorizontalAlignment(SwingConstants.CENTER);

                return l;
            }
        });

    }

    public void menubar() {

        jMenuBar1.setUI(new BasicMenuBarUI() {
            public void paint(Graphics g, JComponent c) {
                g.setColor(new Color(184, 221, 182));

                g.fillRect(0, 0, c.getWidth(), c.getHeight());
            }
        });
    }

    public void tabbedpanel() {

        JLabel lab = new JLabel("Registro Inspección Movil");
        lab.setPreferredSize(new Dimension(110, 35));
        jTabbedPane1.setTabComponentAt(0, lab);

        jTabbedPane1.setUI(new shapeTabbedPaneUI());

    }

    public void reporteorden() {
        Date fechaActual = new Date();
        List lista = new ArrayList();
        lista.clear();
        int verfilax = tableinspeccion.getSelectedRow();

        for (int i = 0; i < tableorden.getRowCount(); i++) {

            rOrden ordenmcxx = new rOrden(
                    tableorden.getValueAt(i, 3).toString(),
                    tableorden.getValueAt(i, 4).toString(),
                    tableorden.getValueAt(i, 5).toString());

            lista.add(ordenmcxx);
        }
        try {
            String master = System.getProperty("user.dir") + "/src/Reportes/rOrden.jasper";

            Map parametro = new HashMap();
//          parametro.put("logo", this.getClass().getResourceAsStream(logotipo));
            parametro.put("fechaActual", Utilidades.formatDate(fechaActual));

            String actividad = (String) tableinspeccion.getValueAt(verfilax, 1);
            parametro.put("actividad", actividad);
//            
            String fecha = (String) tableinspeccion.getValueAt(verfilax, 2);
            parametro.put("fecha", fecha);

            String hora = (String) tableinspeccion.getValueAt(verfilax, 3);
            parametro.put("hora", hora);

            String unidad = (String) tableinspeccion.getValueAt(verfilax, 4);
            parametro.put("unidad", unidad);

            String marca = (String) tableinspeccion.getValueAt(verfilax, 5);
            parametro.put("marca", marca);

            String turno = (String) tableinspeccion.getValueAt(verfilax, 6);
            parametro.put("turno", turno);

            String conductor = (String) tableinspeccion.getValueAt(verfilax, 7);
            parametro.put("conductor", conductor);

            String tecnico = (String) tableinspeccion.getValueAt(verfilax, 8);
            parametro.put("tecnico", tecnico);

            JasperPrint informe = JasperFillManager.fillReport(master, parametro, new JRBeanCollectionDataSource(lista));

            JasperViewer.viewReport(informe, false);
//            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(rpuser.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
