/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.empleado;

import Modelo.Dao;
import Modelo.Departamento;
import Modelo.Empleado;
import Modelo.Pais;
import Modelo.Provincia;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import view.Login;
import static view.empleado.RegisTrabajadores.tableEmpleados;


/**
 *
 * @author Dani
 */
public class nuevoTrab extends javax.swing.JFrame {

    /**
     * Creates new form nuevoUsuario
     */
    Dao dao=new Dao();
    boolean nuevo=false;
    Date fecha  =new Date();
    
    String resultado="",Activo="",Admin="";
    	static Login is;

	String nombreUser = Login.txtusuario.getText();
        String ip;
    public nuevoTrab() {
        initComponents();
        darcolor();
         this.setIconImage(new ImageIcon(getClass().getResource("/images/edit-copy.png")).getImage());

            try {
          ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(nuevoTrab.class.getName()).log(Level.SEVERE, null, ex);
        }

            this.setTitle("Registrar Colaborador. " + nombreUser+"@ServiciosGeneralesViviana " + "[{"+ ip +"}]" );
                txtfechanacimiento.setVisible(false);
                txtfechaingreso.setVisible(false);
                txtfechasalida.setVisible(false);

        Utilidades.generarID();
        
        txtfmodif.setText(Utilidades.formatDate(fecha));
         dao.listarTipoDoc(cbtipodoc);
         dao.listarCargo(cbcargo);
     
       dao.listarDependencia(cbdependencia);
        
       // txt.setText(Utilidades.formatDate(fecha));
        try {
            txtip.setText(InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName());
        } catch (UnknownHostException ex) {
            Logger.getLogger(nuevoTrab.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtuser1.setText(nombreUser);
        dao.listarPais(jcpais);
        txtfechanacimiento.setText("");
        txtfechaingreso.setText("");
        txtfechasalida.setText("");
        txtdoc.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        txttelefono = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ckjefe = new javax.swing.JCheckBox();
        ckactivo = new javax.swing.JCheckBox();
        cbtipodoc = new javax.swing.JComboBox<>();
        txtdireccion = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtdoc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtorga = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txttipoem = new javax.swing.JTextField();
        txttipol = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtip = new javax.swing.JTextField();
        txtuser1 = new javax.swing.JTextField();
        txtfmodif = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ckpermiso = new javax.swing.JCheckBox();
        cbsexo = new javax.swing.JComboBox<>();
        cbdependencia = new javax.swing.JComboBox<>();
        datefi = new com.toedter.calendar.JDateChooser();
        dateft = new com.toedter.calendar.JDateChooser();
        datefn = new com.toedter.calendar.JDateChooser();
        txtidc = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jcpais = new javax.swing.JComboBox<>();
        jcdepartamento = new javax.swing.JComboBox<>();
        jcprovincia = new javax.swing.JComboBox<>();
        jcdistrito = new javax.swing.JComboBox<>();
        txtfechasalida = new javax.swing.JTextField();
        txtfechanacimiento = new javax.swing.JTextField();
        txtfechaingreso = new javax.swing.JTextField();
        txtnl = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cbcargo = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txttelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelefonoKeyTyped(evt);
            }
        });

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        txtemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtemailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtemailKeyTyped(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/applications-system.png"))); // NOI18N
        jButton9.setText("Grabar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jButton9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton9KeyTyped(evt);
            }
        });

        jLabel11.setText("Email");

        jLabel10.setText("Telefono");

        jLabel9.setText("Sexo");

        jLabel8.setText("Distrito");

        ckjefe.setText("Jefe");

        ckactivo.setSelected(true);
        ckactivo.setText("Activo");
        ckactivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ckactivoKeyTyped(evt);
            }
        });

        cbtipodoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtipodocActionPerformed(evt);
            }
        });
        cbtipodoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbtipodocFocusGained(evt);
            }
        });
        cbtipodoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbtipodocKeyTyped(evt);
            }
        });

        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        txtdireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdireccionKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdireccionKeyTyped(evt);
            }
        });

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        txtdoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdocKeyTyped(evt);
            }
        });

        jLabel1.setText("Tipo de documento");

        jLabel2.setText("N° Documento");

        jLabel3.setText("Nombres");

        jLabel4.setText("Direccion");

        jLabel5.setText("Pais");

        jLabel6.setText("Departamento");

        jLabel7.setText("Provincia");

        txtorga.setText("SERVICIOS GENERALES VIVIANA S.A.C");
        txtorga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtorgaKeyTyped(evt);
            }
        });

        jLabel13.setText("Dependencia");

        jLabel14.setText("Organización");

        jLabel15.setText("Tipo de Conductor");

        txttipoem.setText("CONDUCTOR");
        txttipoem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipoemActionPerformed(evt);
            }
        });
        txttipoem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttipoemKeyTyped(evt);
            }
        });

        txttipol.setText("-");
        txttipol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttipolActionPerformed(evt);
            }
        });
        txttipol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttipolKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttipolKeyTyped(evt);
            }
        });

        jLabel16.setText("Tipo de Licencia");

        jLabel17.setText("Fecha de ingreso");

        jLabel18.setText("Fecha de termino");

        txtip.setEditable(false);

        txtuser1.setEditable(false);

        txtfmodif.setEditable(false);

        txtedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtedadKeyTyped(evt);
            }
        });

        jLabel20.setText("Fecha de Nacimiento");

        jLabel21.setText("Edad");

        jLabel22.setText("Fecha Modificación");

        jLabel23.setText("User");

        jLabel24.setText("Ip");

        ckpermiso.setText("Permiso de conducir");

        cbsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsexoActionPerformed(evt);
            }
        });
        cbsexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbsexoFocusGained(evt);
            }
        });
        cbsexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbsexoKeyTyped(evt);
            }
        });

        cbdependencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdependenciaActionPerformed(evt);
            }
        });
        cbdependencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbdependenciaFocusGained(evt);
            }
        });
        cbdependencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbdependenciaKeyTyped(evt);
            }
        });

        datefi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                datefiFocusGained(evt);
            }
        });
        datefi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datefiKeyTyped(evt);
            }
        });

        dateft.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateftKeyTyped(evt);
            }
        });

        datefn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datefnKeyTyped(evt);
            }
        });

        txtidc.setEditable(false);
        txtidc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidcActionPerformed(evt);
            }
        });

        jLabel19.setText("Id");

        jcpais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione" }));
        jcpais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcpaisMouseClicked(evt);
            }
        });
        jcpais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcpaisItemStateChanged(evt);
            }
        });
        jcpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcpaisActionPerformed(evt);
            }
        });
        jcpais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcpaisFocusGained(evt);
            }
        });
        jcpais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcpaisKeyTyped(evt);
            }
        });

        jcdepartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcdepartamentoItemStateChanged(evt);
            }
        });
        jcdepartamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcdepartamentoFocusGained(evt);
            }
        });
        jcdepartamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcdepartamentoKeyTyped(evt);
            }
        });

        jcprovincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcprovinciaItemStateChanged(evt);
            }
        });
        jcprovincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcprovinciaActionPerformed(evt);
            }
        });
        jcprovincia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcprovinciaFocusGained(evt);
            }
        });
        jcprovincia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcprovinciaKeyTyped(evt);
            }
        });

        jcdistrito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcdistritoItemStateChanged(evt);
            }
        });
        jcdistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcdistritoActionPerformed(evt);
            }
        });
        jcdistrito.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcdistritoFocusGained(evt);
            }
        });
        jcdistrito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jcdistritoKeyTyped(evt);
            }
        });

        txtnl.setText("-");
        txtnl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnlActionPerformed(evt);
            }
        });
        txtnl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnlKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnlKeyTyped(evt);
            }
        });

        jLabel27.setText("N° de Licencia");

        cbcargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcargoActionPerformed(evt);
            }
        });
        cbcargo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbcargoFocusGained(evt);
            }
        });
        cbcargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbcargoKeyTyped(evt);
            }
        });

        jLabel25.setText("Puesto de trabajo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel1)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcdistrito, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtdoc)
                                    .addComponent(txtnombre)
                                    .addComponent(txtdireccion)
                                    .addComponent(cbtipodoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcpais, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcdepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jcprovincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbsexo, 0, 176, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10))
                                            .addComponent(datefn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(datefi, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel14)))
                                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbcargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtorga, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                            .addComponent(txtemail)
                                            .addComponent(cbdependencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel23))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtfmodif)
                                                .addComponent(txtuser1)
                                                .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(ckactivo)
                                            .addGap(18, 18, 18)
                                            .addComponent(ckjefe)
                                            .addGap(10, 10, 10)
                                            .addComponent(ckpermiso))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel15)
                                                .addComponent(jLabel16)
                                                .addComponent(jLabel27))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txttipol)
                                                .addComponent(txttipoem, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                                .addComponent(txtnl))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfechasalida, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtidc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbtipodoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtdoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcdepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jcprovincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jcdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbdependencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtorga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txttipoem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttipol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckactivo)
                            .addComponent(ckjefe)
                            .addComponent(ckpermiso))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(txttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datefn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel21)
                                .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(datefi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(dateft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txtfmodif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfechasalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        datefi.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                //Aquí agregaremos la funcionalidad que queremos
                /* edad();
                txtedad.setText(ed);*/

                obtenerFecha2();

                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                // JOptionPane.showMessageDialog(rootPane, "la fecha es "+new Date());
            }
        });
        dateft.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                //Aquí agregaremos la funcionalidad que queremos
                /* edad();
                txtedad.setText(ed);*/

                obtenerFecha3();

                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                // JOptionPane.showMessageDialog(rootPane, "la fecha es "+new Date());
            }
        });
        datefn.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                //Aquí agregaremos la funcionalidad que queremos
                /* edad();
                txtedad.setText(ed);*/

                obtenerFecha1();

                calcularEdad();

                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                // JOptionPane.showMessageDialog(rootPane, "la fecha es "+new Date());
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Empleado empl=new Empleado();  
        nuevo = true;

  if (txtdoc.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el documento de identidad");
           txtdoc.grabFocus();
            return;
        }
            if (txtnombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar nombre del trabajador");
           txtnombre.grabFocus();
            return;
        }
            
              if (datefi.getDate()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar la fecha de ingreso");
            datefi.grabFocus();
            return;
        }
              
              
 empl.setIdempleado(txtidc.getText());
//	empl.setIdempleado("90");System.out.println(txtidc.getText());

empl.setNumdoc(txtdoc.getText());
//	empl.setNumdoc("47978242");System.out.println(txtdoc.getText());

	 empl.setNombres(txtnombre.getText());
//	empl.setNombres("carlos");System.out.println(txtnombre.getText());

	String valor = cbtipodoc.getSelectedItem().toString();
	empl.setIdtipodoc(dao.verificarTipoDoc(valor));
	//empl.setIdtipodoc(1);
//        System.out.println(dao.verificarTipoDoc(valor));
empl.setDirección(txtdireccion.getText());
	//empl.setDirección("calle");System.out.println(txtdireccion.getText());

	String valor1 = jcpais.getSelectedItem().toString();
empl.setPais(valor1);
	//empl.setPais("bolivia");System.out.println(valor1);

	String valor2 = jcdepartamento.getSelectedItem().toString();
empl.setDepartamento(valor2);
	//empl.setDepartamento("bo");System.out.println(valor2);

	String valor3 = jcprovincia.getSelectedItem().toString();
empl.setProvincia(valor3);
	//empl.setProvincia("pro");System.out.println(valor3);

	String valor4 = jcdistrito.getSelectedItem().toString();
empl.setDistrito(valor4);
	//empl.setDistrito("dis");System.out.println(valor4);

	 empl.setSexo(cbsexo.getSelectedItem().toString());
	//empl.setSexo("mas");System.out.println(cbsexo.getSelectedItem().toString());

	empl.setTelefono(txttelefono.getText());
	//empl.setTelefono("960287195");System.out.println(txttelefono.getText());

	 empl.setEmail(txtemail.getText());
	//empl.setEmail("email");System.out.println(txtemail.getText());

	//empl.setPuesto("puesto");System.out.println(txtpuesto.getText());
 if(datefn.getDate()==null){
              txtfechanacimiento.setText("");
        }
          empl.setFecnacimiento(txtfechanacimiento.getText());



	 empl.setEdad(Integer.parseInt(txtedad.getText()));

	String perConducir;
        if(ckpermiso.isSelected())
	{
		perConducir = "1";
	}else
	{
		perConducir = "0";
	}

	 empl.setPerconducir(perConducir);
	//empl.setPerconducir("1");System.out.println(perConducir);

	String valor5 = cbdependencia.getSelectedItem().toString();
	 empl.setIddependencia(dao.verificarDependencia(valor5));
	//empl.setIddependencia(1);
//                                                    
//	System.out.println(dao.verificarDependencia(valor5));


	 empl.setOrganización(txttipoem.getText());
         
	//empl.setOrganización("org");System.out.println(txtorga.getText());

	 empl.setTipoemp(txttipol.getText());
	 empl.setTipolicencia(txttipol.getText());
	 empl.setNlicencia(txtnl.getText());
//	empl.setTipoemp("contra");System.out.println(txttipoe.getText());

	String Activo;if(ckactivo.isSelected())
	{
		Activo = "1";
	}else
	{
		Activo = "0";
	}

	 empl.setActivo(Activo);
	//empl.setActivo("1");System.out.println(Activo);

	String jefe;
        if(ckjefe.isSelected())
	{
		jefe = "1";
	}else
	{
		jefe = "0";
	}

	empl.setJefe(jefe);

	 empl.setFecham(txtfmodif.getText());

	 empl.setNomusum(txtuser1.getText());

	 empl.setIp(txtip.getText());

          if(datefi.getDate()==null){
              txtfechaingreso.setText("");
        }
              	 empl.setFechaIngreso(txtfechaingreso.getText());

       
        
         if(dateft.getDate()==null){
              txtfechasalida.setText("");
        }
              empl.setFechaSalida(txtfechasalida.getText());
      
       	          String valor6 = cbcargo.getSelectedItem().toString();
                  empl.setIdcargo(dao.verificarCARGO(valor6));


                                             
	if (nuevo) {
		resultado = dao.GuardarEmpleado(empl);
		JOptionPane.showMessageDialog(rootPane, resultado);
                dao.mostrarEmpleados("","","","","","");
                tableEmpleados.setRowSelectionInterval(0, 0);

	}
       dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void cbtipodocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtipodocActionPerformed
        //        Rol r = (Rol) jComboBox1.getSelectedItem();
        //		     String id = r.getIdrol();
        //                     dao.listarRol(jComboBox1, id);
    }//GEN-LAST:event_cbtipodocActionPerformed

    private void cbsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbsexoActionPerformed

    private void cbdependenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdependenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdependenciaActionPerformed

    private void jcpaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcpaisMouseClicked

    }//GEN-LAST:event_jcpaisMouseClicked

    private void jcpaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcpaisItemStateChanged

        Pais pais = (Pais) this.jcpais.getSelectedItem();
        int id = pais.getIdPais();
        //de.listar_provincia(jcdepartamento, id);
        dao.listarDepartamento(jcdepartamento, id);
    }//GEN-LAST:event_jcpaisItemStateChanged

    private void jcpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcpaisActionPerformed

    private void jcdepartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcdepartamentoItemStateChanged
        Departamento departamento = (Departamento) this.jcdepartamento.getSelectedItem();
        int id = departamento.getIdDepartamento();
        dao.listarProvincia(jcprovincia, id);
    }//GEN-LAST:event_jcdepartamentoItemStateChanged

    private void jcprovinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcprovinciaItemStateChanged
        Provincia provincia = (Provincia) this.jcprovincia.getSelectedItem();
        int id = provincia.getIdProvincia();
        System.out.println(id);
        dao.listarDistrito(jcdistrito, id);
    }//GEN-LAST:event_jcprovinciaItemStateChanged

    private void jcprovinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcprovinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcprovinciaActionPerformed

    private void jcdistritoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcdistritoItemStateChanged

    }//GEN-LAST:event_jcdistritoItemStateChanged

    private void jcdistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcdistritoActionPerformed

    }//GEN-LAST:event_jcdistritoActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
      
    }//GEN-LAST:event_txtemailActionPerformed

    private void txttipolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipolActionPerformed
       
    }//GEN-LAST:event_txttipolActionPerformed

    private void txtnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyReleased
        String cadena= (txtnombre.getText()).toUpperCase();
 txtnombre.setText(cadena);
    }//GEN-LAST:event_txtnombreKeyReleased

    private void txtdireccionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyReleased
        String cadena= (txtdireccion.getText()).toUpperCase();
 txtdireccion.setText(cadena);
    }//GEN-LAST:event_txtdireccionKeyReleased

    private void txtemailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailKeyReleased

    private void txttipolKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttipolKeyReleased
        String cadena= (txttipol.getText()).toUpperCase();
 txttipol.setText(cadena);
    }//GEN-LAST:event_txttipolKeyReleased

    private void txtnlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnlActionPerformed

    private void txtnlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnlKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnlKeyReleased

    private void txtdocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdocKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtnombre.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txtdocKeyTyped

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtdireccion.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtdireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdireccionKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jcpais.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txtdireccionKeyTyped

    private void jcpaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcpaisKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jcdepartamento.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_jcpaisKeyTyped

    private void jcdepartamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcdepartamentoKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jcprovincia.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_jcdepartamentoKeyTyped

    private void jcprovinciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcprovinciaKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                ckactivo.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_jcprovinciaKeyTyped

    private void ckactivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ckactivoKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                cbdependencia.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_ckactivoKeyTyped

    private void cbdependenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbdependenciaKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtorga.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_cbdependenciaKeyTyped

    private void txtorgaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtorgaKeyTyped
          char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txttipoem.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txtorgaKeyTyped

    private void txttipoemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttipoemKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txttipol.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txttipoemKeyTyped

    private void txttipolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttipolKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtnl.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txttipolKeyTyped

    private void txtnlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnlKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                datefi.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txtnlKeyTyped

    private void datefiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datefiKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                dateft.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_datefiKeyTyped

    private void dateftKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateftKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jcdistrito.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_dateftKeyTyped

    private void cbsexoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbsexoKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txttelefono.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_cbsexoKeyTyped

    private void jcdistritoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcdistritoKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                cbsexo.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_jcdistritoKeyTyped

    private void txttelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelefonoKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtemail.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txttelefonoKeyTyped

    private void txtemailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtemailKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                datefn.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txtemailKeyTyped

    private void datefnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datefnKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtedad.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_datefnKeyTyped

    private void txtedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jButton9.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txtedadKeyTyped

    private void jButton9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton9KeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                jButton9.doClick();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_jButton9KeyTyped

    private void cbtipodocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbtipodocKeyTyped
         char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtdoc.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_cbtipodocKeyTyped

    private void cbtipodocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbtipodocFocusGained
        cbtipodoc.showPopup();
    }//GEN-LAST:event_cbtipodocFocusGained

    private void jcpaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcpaisFocusGained
jcpais.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_jcpaisFocusGained

    private void jcdepartamentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcdepartamentoFocusGained
jcdepartamento.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_jcdepartamentoFocusGained

    private void jcprovinciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcprovinciaFocusGained
jcprovincia.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_jcprovinciaFocusGained

    private void cbdependenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbdependenciaFocusGained
cbdependencia.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_cbdependenciaFocusGained

    private void jcdistritoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcdistritoFocusGained
jcdistrito.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_jcdistritoFocusGained

    private void cbsexoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbsexoFocusGained
cbsexo.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_cbsexoFocusGained

    private void datefiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datefiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_datefiFocusGained

    private void txttipoemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttipoemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttipoemActionPerformed

    private void cbcargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcargoActionPerformed

    private void cbcargoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbcargoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcargoFocusGained

    private void cbcargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbcargoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcargoKeyTyped

    private void txtidcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoTrab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoTrab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoTrab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoTrab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoTrab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cbcargo;
    public static javax.swing.JComboBox<String> cbdependencia;
    public static javax.swing.JComboBox<String> cbsexo;
    public static javax.swing.JComboBox<String> cbtipodoc;
    public static javax.swing.JCheckBox ckactivo;
    public static javax.swing.JCheckBox ckjefe;
    public static javax.swing.JCheckBox ckpermiso;
    public static com.toedter.calendar.JDateChooser datefi;
    public static com.toedter.calendar.JDateChooser datefn;
    public static com.toedter.calendar.JDateChooser dateft;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JComboBox<String> jcdepartamento;
    public static javax.swing.JComboBox<String> jcdistrito;
    public static javax.swing.JComboBox<String> jcpais;
    public static javax.swing.JComboBox<String> jcprovincia;
    public static javax.swing.JTextField txtdireccion;
    public static javax.swing.JTextField txtdoc;
    public static javax.swing.JTextField txtedad;
    public static javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfechaingreso;
    private javax.swing.JTextField txtfechanacimiento;
    private javax.swing.JTextField txtfechasalida;
    public static javax.swing.JTextField txtfmodif;
    public static javax.swing.JTextField txtidc;
    public static javax.swing.JTextField txtip;
    public static javax.swing.JTextField txtnl;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtorga;
    public static javax.swing.JTextField txttelefono;
    public static javax.swing.JTextField txttipoem;
    public static javax.swing.JTextField txttipol;
    public static javax.swing.JTextField txtuser1;
    // End of variables declaration//GEN-END:variables
 public void obtenerFecha1() {
        String rx1 = Utilidades.formatDate(datefn.getDate());
        txtfechanacimiento.setText(rx1);
    }
  public void obtenerFecha2() {
        String rx2 = Utilidades.formatDate(datefi.getDate());
        txtfechaingreso.setText(rx2);
    }
   public void obtenerFecha3() {
        String rx3 = Utilidades.formatDate(dateft.getDate());
        txtfechasalida.setText(rx3);
    }
   
   public void darcolor(){
                cbtipodoc.setBackground(new Color(255,255,153)); 
txtdoc.setBackground(new Color(255,255,153)); 
txtnombre.setBackground(new Color(255,255,153)); 
txtdireccion.setBackground(new Color(255,255,153)); 
jcpais.setBackground(new Color(255,255,153)); 
jcdepartamento.setBackground(new Color(255,255,153)); 
jcprovincia.setBackground(new Color(255,255,153)); 
jcdistrito.setBackground(new Color(255,255,153)); 
cbsexo.setBackground(new Color(255,255,153)); 
            txttelefono.setBackground(new Color(255,255,153)); 
            txtemail.setBackground(new Color(255,255,153)); 
//            datefn.setBackground(new Color(255,255,153)); 
//            datefi.setBackground(new Color(255,255,153)); 
            ckactivo.setBackground(new Color(255,255,153)); 
//            dateft.setBackground(new Color(255,255,153)); 
            ckjefe.setBackground(new Color(255,255,153)); 
            ckpermiso.setBackground(new Color(255,255,153)); 
            txtedad.setBackground(new Color(255,255,153)); 
                
            cbdependencia.setBackground(new Color(255,255,153)); 
            cbcargo.setBackground(new Color(255,255,153)); 
            txtorga.setBackground(new Color(255,255,153)); 
            txttipoem.setBackground(new Color(255,255,153)); 
            txttipol.setBackground(new Color(255,255,153)); 
            txtnl.setBackground(new Color(255,255,153)); 
   }
   
       /*calcular la edad**/
    public void calcularEdad() {

        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("yyyy");
        int f1 = Integer.parseInt(f.format(d));

        String f2 = Utilidades.formatDate2(datefn.getDate());
        int f3 = Integer.valueOf(f2);

        int edad = f1 - f3;

        String r = String.valueOf(edad);

        txtedad.setText(r);

    }
}
