/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.mantenimiento;

import Modelo.Dao;
import Modelo.Mantenimiento_;
import Utilidades.Utilidades;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import view.Login;
import static view.entradasalidas.nuevovht.datefs;
import static view.mantenimiento.Mantenimiento.tablemantenimiento;

/**
 *
 * @author Dani
 */
public class nuevoMant extends javax.swing.JFrame {

    /**
     * Creates new form nuevoMant
     */
    public static boolean estadoxy=false;
    public static boolean estadocrearR_=false;
    public static boolean estadocrearS_=false;
    Dao dao=new Dao();
    Date fecha =new Date();
    boolean nuevo=false;
    String resultado="";
    	static Login is;
String ip;
	String nombreUser = Login.txtusuario.getText();
    
    public nuevoMant() {
        initComponents();
        
        ptable();
        ptable2();
        darcolor();
        
         this.setIconImage(new ImageIcon(getClass().getResource("/images/format-justify-fill.png")).getImage());

            try {
          ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(nuevoDetalleR.class.getName()).log(Level.SEVERE, null, ex);
        }

            this.setTitle("Nuevo registro. " + nombreUser+"@ServiciosGeneralesViviana " + "[{"+ ip +"}]" );
        
                nuevoMant.txt1.setText("");
        nuevoMant.txt2.setText("");
        nuevoMant.txt3.setText("");
        
         datefa.setText(Utilidades.formatDate(fecha));
     
        
        try {
            txtip.setText(InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName());
        } catch (UnknownHostException ex) {
            Logger.getLogger(nuevoMant.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtuser.setText(nombreUser);
        
        dao.listarTipoMant(cbtm);
        Utilidades.generarIdMant();
        txt1.setVisible(false);
        txt2.setVisible(false);
        txt3.setVisible(false);
        
        l1.setVisible(false);
        l2.setVisible(false);
        l3.setVisible(false);
        
        datefa.setVisible(false);
        txtuser.setVisible(false);
        txtip.setVisible(false);
        cbtm.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnnuevos = new javax.swing.JButton();
        btnnuevor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablenuevoResp = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableservmant = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtide = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnomp = new javax.swing.JTextField();
        datefechamant = new com.toedter.calendar.JDateChooser();
        btnempleado1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtnomv = new javax.swing.JTextField();
        btnempleado2 = new javax.swing.JButton();
        txtidv = new javax.swing.JTextField();
        txtidp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnempleado3 = new javax.swing.JButton();
        dateultimarevision = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtdiasv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        datesiguienterevision = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtip = new javax.swing.JTextField();
        txtuser = new javax.swing.JTextField();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        datefa = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtimporte = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbtm = new javax.swing.JComboBox<>();
        btng = new javax.swing.JButton();
        txt1 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txturk = new javax.swing.JTextField();
        txtvk = new javax.swing.JTextField();
        txtsrk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));

        btnnuevos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png"))); // NOI18N
        btnnuevos.setText(" Agregar nuevo servicio");
        btnnuevos.setEnabled(false);
        btnnuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevosActionPerformed(evt);
            }
        });

        btnnuevor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_1.png"))); // NOI18N
        btnnuevor.setText(" Agregar nuevo repuesto");
        btnnuevor.setEnabled(false);
        btnnuevor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevorActionPerformed(evt);
            }
        });

        tablenuevoResp.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablenuevoResp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablenuevoResp.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tablenuevoResp.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tablenuevoResp);

        tableservmant.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tableservmant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableservmant.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tableservmant.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(tableservmant);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jLabel3.setText("Codigo");

        txtcodigo.setEditable(false);
        txtcodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        txtnome.setEditable(false);
        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomeKeyTyped(evt);
            }
        });

        txtide.setEditable(false);
        txtide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtideActionPerformed(evt);
            }
        });

        jLabel5.setText("Empleado");

        jLabel6.setText("Fecha de Mant.");

        jLabel7.setText("Proveedor");

        txtnomp.setEditable(false);
        txtnomp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnompActionPerformed(evt);
            }
        });
        txtnomp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnompKeyTyped(evt);
            }
        });

        datefechamant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datefechamantKeyTyped(evt);
            }
        });

        btnempleado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-find.png"))); // NOI18N
        btnempleado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempleado1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Vehiculo");

        txtnomv.setEditable(false);
        txtnomv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomvKeyTyped(evt);
            }
        });

        btnempleado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-users.png"))); // NOI18N
        btnempleado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempleado2ActionPerformed(evt);
            }
        });

        txtidv.setEditable(false);

        txtidp.setEditable(false);

        jLabel8.setText("Importe");

        btnempleado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/folder-saved-search.png"))); // NOI18N
        btnempleado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempleado3ActionPerformed(evt);
            }
        });

        dateultimarevision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateultimarevisionKeyTyped(evt);
            }
        });

        jLabel9.setText("Ultima revisión");

        txtdiasv.setText("0");
        txtdiasv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtdiasvFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdiasvFocusGained(evt);
            }
        });
        txtdiasv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdiasvKeyTyped(evt);
            }
        });

        jLabel10.setText("Dias vencidos");

        jLabel11.setText("Siguiente revisión");

        datesiguienterevision.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datesiguienterevisionKeyTyped(evt);
            }
        });

        jLabel1.setText("Ultima revision km");

        jLabel2.setText("Vencimiento de km");

        jLabel14.setText("Siguiente revision km");

        txtip.setEnabled(false);
        txtip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtipActionPerformed(evt);
            }
        });

        txtuser.setEnabled(false);

        l2.setText("Usuario");

        l3.setText("Ip");

        datefa.setEnabled(false);

        l1.setText("Fecha de Actualización");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        txtimporte.setText("0.00");
        txtimporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtimporteFocusGained(evt);
            }
        });
        txtimporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtimporteKeyTyped(evt);
            }
        });

        jLabel12.setText("Tipo");

        cbtm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtmActionPerformed(evt);
            }
        });
        cbtm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbtmFocusGained(evt);
            }
        });
        cbtm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cbtmKeyTyped(evt);
            }
        });

        btng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/applications-system.png"))); // NOI18N
        btng.setText("Grabar");
        btng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngActionPerformed(evt);
            }
        });
        btng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btngKeyTyped(evt);
            }
        });

        txt1.setEditable(false);
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });

        txt3.setEditable(false);

        txt2.setEditable(false);

        txturk.setText("0");
        txturk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txturkActionPerformed(evt);
            }
        });
        txturk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txturkFocusGained(evt);
            }
        });
        txturk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txturkKeyTyped(evt);
            }
        });

        txtvk.setText("0");
        txtvk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvkActionPerformed(evt);
            }
        });
        txtvk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtvkFocusGained(evt);
            }
        });
        txtvk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvkKeyTyped(evt);
            }
        });

        txtsrk.setText("0");
        txtsrk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsrkActionPerformed(evt);
            }
        });
        txtsrk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsrkFocusGained(evt);
            }
        });
        txtsrk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsrkKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(datefechamant, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(txtnombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtdiasv)
                                    .addComponent(txtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtide, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtidv, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtidp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtnomv, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                            .addComponent(txtnomp, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnome))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnempleado1)
                                            .addComponent(btnempleado3)
                                            .addComponent(btnempleado2)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbtm, 0, 310, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(153, 153, 153)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateultimarevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datesiguienterevision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btng, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addComponent(txturk)
                            .addComponent(txtvk)
                            .addComponent(txtsrk))
                        .addGap(1307, 1307, 1307))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(datefa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(l3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txturk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtvk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtsrk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(dateultimarevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datesiguienterevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(btng, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbtm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtdiasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(txtimporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(datefechamant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnempleado1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtnomp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtidp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnempleado3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtnomv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtidv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnempleado2))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l1)
                            .addComponent(datefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l3)
                            .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        datefechamant.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                //Aquí agregaremos la funcionalidad que queremos
                /* edad();
                txtedad.setText(ed);*/

                obtenerFecha1();

                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                // JOptionPane.showMessageDialog(rootPane, "la fecha es "+new Date());
            }
        });
        dateultimarevision.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                //Aquí agregaremos la funcionalidad que queremos
                /* edad();
                txtedad.setText(ed);*/

                obtenerFecha2();

                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                // JOptionPane.showMessageDialog(rootPane, "la fecha es "+new Date());
            }
        });
        datesiguienterevision.getDateEditor().addPropertyChangeListener(new java.beans.PropertyChangeListener(){
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                //Aquí agregaremos la funcionalidad que queremos
                /* edad();
                txtedad.setText(ed);*/

                obtenerFecha3();

                //por ejemplo al seleccionar una fecha le mostrare un diálogo con la fecha de hoy
                // JOptionPane.showMessageDialog(rootPane, "la fecha es "+new Date());
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnuevor, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnnuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnuevor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnnuevos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnempleado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempleado1ActionPerformed
        buscarprov bpvx =new buscarprov();
        bpvx.setVisible(true);
        bpvx.setLocationRelativeTo(null);
        estadoxy=true;
        
    }//GEN-LAST:event_btnempleado1ActionPerformed

    private void btnempleado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempleado2ActionPerformed
        buscarempleado bee =new buscarempleado();
        bee.setVisible(true);
        bee.setLocationRelativeTo(null);
        estadoxy=true;
    }//GEN-LAST:event_btnempleado2ActionPerformed

    private void btnempleado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempleado3ActionPerformed
        buscarvehiculo bvv =new buscarvehiculo();
        bvv.setVisible(true);
        bvv.setLocationRelativeTo(null);
        estadoxy=true;
    }//GEN-LAST:event_btnempleado3ActionPerformed

    private void txtipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtipActionPerformed

    private void btngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngActionPerformed
       
        nuevo=true;int cant;
         if (cbtm.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar tipo de mantenimiento");
            cbtm.grabFocus();
            return;
        }
         
          if (txtidv.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el codigo del vehiculo");
           txtnomv.grabFocus();
            return;
        }
          
           if (txtnombre.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar nombre de actividad");
           txtnombre.grabFocus();
            return;
        }
            if (txtnomv.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar el nombre del vehiculo");
           txtnomv.grabFocus();
            return;
        }
                          
              if (!Utilidades.isNumeric(txtdiasv.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor numerico");
            txtdiasv.setText("");
            txtdiasv.grabFocus();
            return;
        } 
             
              cant=Integer.parseInt(txtdiasv.getText());
              if (cant<0) {
                JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor mayor o igual a '0' ");
                txtdiasv.setText("");
                txtdiasv.grabFocus();
                return;
                } 
              
                  if (!Utilidades.isDecimal(txtimporte.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor numerico");
            txtimporte.setText("");
            txtimporte.grabFocus();
            return;
        } 
                double importe=Double.parseDouble(txtimporte.getText());
              if ((importe<0) || (importe<0.00) ) {
                JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor mayor o igual a '0' ");
                txtimporte.setText("");
                txtimporte.grabFocus();
                return;
                }  
                  
                      if (!Utilidades.isNumeric(txturk.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor numerico");
            txturk.setText("");
            txturk.grabFocus();
            return;
        } 
                      double urk=Double.parseDouble(txturk.getText());
              if ((urk<0) || (urk<0.00) ) {
                JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor mayor o igual a '0' ");
                txturk.setText("");
                txturk.grabFocus();
                return;
                }
                          if (!Utilidades.isNumeric(txtvk.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor numerico");
            txtvk.setText("");
            txtvk.grabFocus();
            return;
        } 
                          
                      double vk=Double.parseDouble(txtvk.getText());
              if ((vk<0) || (vk<0.00) ) {
                JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor mayor o igual a '0' ");
                txtvk.setText("");
                txtvk.grabFocus();
                return;
                }
                              if (!Utilidades.isNumeric(txtsrk.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor numerico");
            txtsrk.setText("");
            txtsrk.grabFocus();
            return;
        } 
                                double srk=Double.parseDouble(txtsrk.getText());
              if ((srk<0) || (srk<0.00) ) {
                JOptionPane.showMessageDialog(rootPane, "Debe digitar un valor mayor o igual a '0' ");
                txtsrk.setText("");
                txtsrk.grabFocus();
                return;
                }
                             
                              if (datefechamant.getDate()==null) {
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar la fecha de actividad");
//            datefechamant.setDate(null);
            datefechamant.grabFocus();
            return;
        } 
                              
                              
            Mantenimiento_ mt=new Mantenimiento_();

           mt.setIDMANTENIMIENTO(txtcodigo.getText());
           mt.setNOMBRE(txtnombre.getText());
           
           
           mt.setIMPORTE(Double.parseDouble(txtimporte.getText()));
           
            if(datefechamant.getDate()==null){
              txt1.setText("");
           }
           mt.setFECHAMANT(txt1.getText());
           mt.setIdproveedor(txtidp.getText());
           
          String valor=cbtm.getSelectedItem().toString();
	   mt.setIdtipom(dao.verificarTipoMantenimiento(valor));
           
           if(dateultimarevision.getDate()==null){
              txt2.setText("");
           }
           mt.setULTIMAREV(txt2.getText());
           
           mt.setDIASVEN(Integer.parseInt(txtdiasv.getText()));
           
            if(datesiguienterevision.getDate()==null){
              txt3.setText("");
           }
           mt.setSIGUIENTEREV(txt3.getText());
           mt.setULTIMAREVKM(Double.parseDouble(txturk.getText()));
           mt.setVENCIMIENTOKM(Double.parseDouble(txtvk.getText()));
           mt.setSIGTREVKM(Double.parseDouble(txtsrk.getText()));
           mt.setIdvehiculo(txtidv.getText());
           mt.setIdempleado(txtide.getText());
           mt.setFECHAM(datefa.getText());
           mt.setNOMUSUM(txtuser.getText());
           mt.setIP(txtip.getText());
           
           mt.setMaquina(txtnomv.getText());
           mt.setRazonsocial(txtnomp.getText());
            mt.setNomempleado(txtnome.getText());

           
          
            if(nuevo){
                resultado=dao.GuardarMantenimiento(mt);
                JOptionPane.showMessageDialog(rootPane, resultado);
                btnnuevor.setEnabled(true);
                btnnuevos.setEnabled(true);
               

                 dao.mostrarManteniento("", "", "", "", "");
                          tablemantenimiento.setRowSelectionInterval(0, 0);
btng.setEnabled(false);
//                enableFalse();

            }
//            dispose();  
        
        
        
        
        
        
    }//GEN-LAST:event_btngActionPerformed

    private void btnnuevorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevorActionPerformed
             nuevoDetalleR nrttxx=new nuevoDetalleR();
            nrttxx.setVisible(true);
            nrttxx.setLocationRelativeTo(null);
        
            
    }//GEN-LAST:event_btnnuevorActionPerformed

    private void btnnuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevosActionPerformed
        nuevoDetalleS nsxxaa=new nuevoDetalleS();
            nsxxaa.setVisible(true);
            nsxxaa.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnnuevosActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnompActionPerformed

    private void txtideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtideActionPerformed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyPressed

    private void cbtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtmActionPerformed
        txtnombre.setText(cbtm.getSelectedItem().toString());
    }//GEN-LAST:event_cbtmActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void txturkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txturkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txturkActionPerformed

    private void txtvkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvkActionPerformed

    private void txtsrkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsrkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrkActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtdiasvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdiasvFocusLost
    }//GEN-LAST:event_txtdiasvFocusLost

    private void txtdiasvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdiasvFocusGained
        if(txtdiasv.getText().trim().toLowerCase().equals("0")){
	txtdiasv.setText("");
}
    }//GEN-LAST:event_txtdiasvFocusGained

    private void txtimporteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtimporteFocusGained
        if(txtimporte.getText().trim().toLowerCase().equals("0.00")){
	txtimporte.setText("");
        }
    }//GEN-LAST:event_txtimporteFocusGained

    private void txturkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txturkFocusGained
        if(txturk.getText().trim().toLowerCase().equals("0")){
	 txturk.setText("");
        }
    }//GEN-LAST:event_txturkFocusGained

    private void txtvkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvkFocusGained
          if(txtvk.getText().trim().toLowerCase().equals("0")){
	 txtvk.setText("");
        }
    }//GEN-LAST:event_txtvkFocusGained

    private void txtsrkFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsrkFocusGained
         if(txtsrk.getText().trim().toLowerCase().equals("0")){
	 txtsrk.setText("");
        }
    }//GEN-LAST:event_txtsrkFocusGained

    private void cbtmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbtmKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                datefechamant.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            } // TODO add your handling code here:
    }//GEN-LAST:event_cbtmKeyTyped

    private void datefechamantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datefechamantKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtdiasv.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_datefechamantKeyTyped

    private void txtdiasvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiasvKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtimporte.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiasvKeyTyped

    private void txtimporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtimporteKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtnomp.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtimporteKeyTyped

    private void txtnompKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnompKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtnomv.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
    }//GEN-LAST:event_txtnompKeyTyped

    private void txtnomvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomvKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtnome.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomvKeyTyped

    private void txtnomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txturk.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeKeyTyped

    private void txturkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txturkKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtvk.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txturkKeyTyped

    private void txtvkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvkKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                txtsrk.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtvkKeyTyped

    private void txtsrkKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsrkKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                dateultimarevision.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_txtsrkKeyTyped

    private void dateultimarevisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateultimarevisionKeyTyped
        char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                datesiguienterevision.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            } // TODO add your handling code here:
    }//GEN-LAST:event_dateultimarevisionKeyTyped

    private void datesiguienterevisionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datesiguienterevisionKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
                btng.grabFocus();
            }
        
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }        // TODO add your handling code here:
    }//GEN-LAST:event_datesiguienterevisionKeyTyped

    private void btngKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btngKeyTyped
 char cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ENTER){
               btng.doClick();
            }
          
         cTeclaPresionada=evt.getKeyChar();
        if(cTeclaPresionada==KeyEvent.VK_ESCAPE){
                 dispose();
            }
              // TODO add your handling code here:
    }//GEN-LAST:event_btngKeyTyped

    private void cbtmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbtmFocusGained
cbtm.showPopup();        // TODO add your handling code here:
    }//GEN-LAST:event_cbtmFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nuevoMant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nuevoMant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nuevoMant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nuevoMant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nuevoMant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnempleado1;
    private javax.swing.JButton btnempleado2;
    private javax.swing.JButton btnempleado3;
    private javax.swing.JButton btng;
    private javax.swing.JButton btnnuevor;
    private javax.swing.JButton btnnuevos;
    public static javax.swing.JComboBox<String> cbtm;
    public static javax.swing.JTextField datefa;
    public static com.toedter.calendar.JDateChooser datefechamant;
    public static com.toedter.calendar.JDateChooser datesiguienterevision;
    public static com.toedter.calendar.JDateChooser dateultimarevision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    public static javax.swing.JTable tablenuevoResp;
    public static javax.swing.JTable tableservmant;
    public static javax.swing.JTextField txt1;
    public static javax.swing.JTextField txt2;
    public static javax.swing.JTextField txt3;
    public static javax.swing.JTextField txtcodigo;
    public static javax.swing.JTextField txtdiasv;
    public static javax.swing.JTextField txtide;
    public static javax.swing.JTextField txtidp;
    public static javax.swing.JTextField txtidv;
    public static javax.swing.JTextField txtimporte;
    public static javax.swing.JTextField txtip;
    public static javax.swing.JTextField txtnombre;
    public static javax.swing.JTextField txtnome;
    public static javax.swing.JTextField txtnomp;
    public static javax.swing.JTextField txtnomv;
    public static javax.swing.JTextField txtsrk;
    public static javax.swing.JTextField txturk;
    public static javax.swing.JTextField txtuser;
    public static javax.swing.JTextField txtvk;
    // End of variables declaration//GEN-END:variables
    public void obtenerFecha1() {
        String z = Utilidades.formatDate(datefechamant.getDate());
        txt1.setText(z);
    }
  public void obtenerFecha2() {
        String a = Utilidades.formatDate(dateultimarevision.getDate());
        txt2.setText(a);
    }
   public void obtenerFecha3() {
        String q = Utilidades.formatDate(datesiguienterevision.getDate());
        txt3.setText(q);
    }
   
   public void ptable(){
	
tablenuevoResp.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            l.setBorder(new LineBorder(new Color(239,242,210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                 l.setBackground(new Color(184,221,182)); 
               
l.setHorizontalAlignment(SwingConstants.CENTER) ;

            return l;
        }
    });
	
}
   public void ptable2(){
	
tableservmant.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            l.setBorder(new LineBorder(new Color(239,242,210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                 l.setBackground(new Color(184,221,182)); 
               
l.setHorizontalAlignment(SwingConstants.CENTER) ;

            return l;
        }
    });
	
}
    public void darcolor(){
        txtdiasv.setBackground(new Color(255,255,153));
        txtnombre.setBackground(new Color(255,255,153));
  txtimporte.setBackground(new Color(255,255,153));
  cbtm.setBackground(new Color(255,255,153));
 txturk.setBackground(new Color(255,255,153));
 txtvk.setBackground(new Color(255,255,153));
txtsrk.setBackground(new Color(255,255,153));
datefechamant.setBackground(new Color(255,255,153));
dateultimarevision.setBackground(new Color(255,255,153));
        datesiguienterevision.setBackground(new Color(255,255,153));
        txtnomv.setBackground(new Color(255,255,153));
                txtnomp.setBackground(new Color(255,255,153));
                txtnome.setBackground(new Color(255,255,153));
                txtidp.setBackground(new Color(255,255,153));
                        txtidv.setBackground(new Color(255,255,153));
                        txtide.setBackground(new Color(255,255,153));
     }
}
