/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.entradasalidas;

import Modelo.Dao;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.border.LineBorder;
import javax.swing.plaf.basic.BasicMenuBarUI;
import javax.swing.table.DefaultTableCellRenderer;
import swing.xp.shapeTabbedPaneUI;
import view.Login;

/**
 *
 * @author Dani
 */
public class RegistMP extends javax.swing.JFrame {

    /**
     * Creates new form registActividades
     */
    Dao dao= new Dao();
       public static int indice;

     static Login is;
     String ip;
    String nombreUser = Login.txtusuario.getText();  

    public RegistMP() {
        initComponents();
           
        ptable();
        menubar();
        tabbedpanel();
        
          this.setIconImage(new ImageIcon(getClass().getResource("/images/folder-saved-search.png")).getImage());

            try {
          ip = InetAddress.getLocalHost().getHostAddress() + " - " + InetAddress.getLocalHost().getHostName();
        } catch (UnknownHostException ex) {
            Logger.getLogger(RegistMP.class.getName()).log(Level.SEVERE, null, ex);
        }

            this.setTitle("Entrada y Salida de Maquinaria Pesada.  " + nombreUser+"@ServiciosGeneralesViviana " + "[{"+ ip +"}]" );
            int j=1;

       cantidadRegist(j);
       
        dao.mostrarEntradaSalidasMP("", "", "","");
         table.setRowSelectionInterval(0, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by Pthe Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btndouwn = new javax.swing.JButton();
        btnup = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        cantidad = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table.setSelectionBackground(new java.awt.Color(255, 255, 0));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(table);

        jTabbedPane1.addTab("tab1", jScrollPane2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-paste.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-search.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Calendar_16x16.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btndouwn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-down.png"))); // NOI18N
        btndouwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndouwnActionPerformed(evt);
            }
        });

        btnup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/go-up.png"))); // NOI18N
        btnup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document-print_1.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/system-log-out.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view-refresh.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btndouwn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(btndouwn)
                    .addComponent(btnup)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        cantidad.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cantidad.setForeground(new java.awt.Color(0, 51, 255));
        cantidad.setText("jLabel1");

        jButton8.setBackground(new java.awt.Color(184, 221, 182));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/brain_2.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("SAFV - SISTEMA DE ADMINISTRACIÓN DE FLOTA VEHICULAR - SERVICIOS GENERALES VIVIANA EIRL");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setPreferredSize(new java.awt.Dimension(324, 29));

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem2.setText("Ver");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Herramientas");
        jMenu5.add(jSeparator2);

        jMenuItem3.setText("Menu principal");
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator4);

        jMenuItem4.setText("Submenu");
        jMenu5.add(jMenuItem4);

        jMenuBar1.add(jMenu5);

        jMenu9.setText("Sistemas");

        jMenuItem5.setText("Procesos");
        jMenu9.add(jMenuItem5);

        jMenuBar1.add(jMenu9);

        jMenu11.setText("Reportes");

        jMenuItem6.setText("Imprimir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem6);

        jMenuBar1.add(jMenu11);

        jMenu14.setText("Ayuda");

        jMenuItem7.setText("?");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem7);

        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            nuevomp esxc=new nuevomp();
            esxc.setVisible(true);
            esxc.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       SearchMP bes1MP=new SearchMP();
        bes1MP.setVisible(true);
        bes1MP.setLocationRelativeTo(null);   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             verfilas();      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btndouwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndouwnActionPerformed
         
         down();
     
    
    }//GEN-LAST:event_btndouwnActionPerformed

    private void btnupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupActionPerformed
        
         up();
     
    
    }//GEN-LAST:event_btnupActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

    dao.mostrarEntradaSalidasMP("", "", "","");
         table.setRowSelectionInterval(0, 0);
     

    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

    reporteES2 esreportexy2=new reporteES2();
        esreportexy2.setVisible(true);
        esreportexy2.setLocationRelativeTo(null);


        
      
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
//       verfilas();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
//       reporte();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        User userxy=new User();
        userxy.setVisible(true);
        userxy.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
  jTabbedPane1.getSelectedIndex();
    indice = jTabbedPane1.getSelectedIndex(); 
    

// TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndouwn;
    private javax.swing.JButton btnup;
    public static javax.swing.JLabel cantidad;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    public static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
 public void menubar(){
	
jMenuBar1.setUI ( new BasicMenuBarUI ()
    {
        public void paint ( Graphics g, JComponent c )
        {
            g.setColor (new Color(184,221,182));
            
            g.fillRect ( 0, 0, c.getWidth (), c.getHeight () );
        }
    } );
}

public void tabbedpanel(){
JLabel lab = new JLabel("Maquinaria Pesada"); 
lab.setPreferredSize(new Dimension(150, 35)); 
jTabbedPane1.setTabComponentAt(0, lab);
jTabbedPane1.setUI( new shapeTabbedPaneUI() );

}


public void ptable(){
	
table.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer(){

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

            l.setBorder(new LineBorder(new Color(239,242,210), 1));

//            l.setBackground(Color.green);
//                 l.setBackground(Color.getHSBColor(800, 40, 31)); 
                 l.setBackground(new Color(184,221,182)); 
               
l.setHorizontalAlignment(SwingConstants.CENTER) ;

            return l;
        }
    });
	
}

public void up(){
    int index=0;
    index = table.getSelectedRow();
                if(index > 0){
                    table.setRowSelectionInterval(index - 1, index - 1);
                    btndouwn.setEnabled(true);
                    cantidadRegist(index);
                }else{
                    btnup.setEnabled(false);
                    btndouwn.setEnabled(true);
                }
        }

   public void down(){
        int index;
        index = table.getSelectedRow();
                if(table.getRowCount()>(index+1)){
                         table.setRowSelectionInterval(index + 1, index + 1);
                         cantidadRegist(index + 2);
                     btnup.setEnabled(true);
                    }else{
                   btndouwn.setEnabled(false);
                   btnup.setEnabled(true);
                }
        }
   
    
    
    public void cantidadRegist(int j){
      	    int fila = table.getSelectedRow();
            int x = 0;
            for (int i = 0; i < table.getRowCount(); i++){
                     x++;
                }
            cantidad.setText("["+j+"/"+String.valueOf(x)+"]");
  }
    
    public void  verfilas(){
        
            int filaES = table.getSelectedRow();
            Date Fechas=null,FechaE=null;

            if(filaES<0){
                JOptionPane.showMessageDialog(rootPane, "no ha seleccionado ningun registro");

            }else{
                
                ActualizarMP actes = new ActualizarMP();
                actes.setVisible(true);
                actes.setLocationRelativeTo(null);

               ActualizarMP.txtid.setText(table.getValueAt(filaES, 0).toString());
                ActualizarMP.txtidv.setText(table.getValueAt(filaES, 1).toString());
                
                      String cxy=table.getModel().getValueAt(filaES, 2).toString();
                        if(cxy.equals("")){
                             Date fvaciaxy=null;
                            ActualizarMP.datefs.setDate(fvaciaxy); 
                            ActualizarMP.txt1.setText("");
                        }else{
                           try {
                                    Fechas = new SimpleDateFormat("yyyy-MM-dd").parse((String)table.getValueAt(filaES, 2).toString());
                                } catch (ParseException ex) {
                                    Logger.getLogger(RegistMP.class.getName()).log(Level.SEVERE, null, ex);
                                }
                  ActualizarMP.datefs.setDate(Fechas);
                        }
                        
                  ActualizarMP.txths.setText(table.getValueAt(filaES, 3).toString());
                  
                   String cxy2=table.getModel().getValueAt(filaES, 4).toString();
                        if(cxy.equals("")){
                             Date fvaciaxy=null;
                            ActualizarMP.datefe.setDate(fvaciaxy); 
                            ActualizarMP.txt2.setText("");
                        }else{
                           try {
                                    FechaE = new SimpleDateFormat("yyyy-MM-dd").parse((String)table.getValueAt(filaES, 4).toString());
                                } catch (ParseException ex) {
                                    Logger.getLogger(RegistMP.class.getName()).log(Level.SEVERE, null, ex);
                                }
                  ActualizarMP.datefe.setDate(FechaE);
                        }
                        
                  ActualizarMP.txthe.setText(table.getValueAt(filaES, 5).toString());
                  
                  ActualizarMP.txtoperador.setText(table.getValueAt(filaES, 6).toString());
                    ActualizarMP.txtparte.setText(table.getValueAt(filaES, 7).toString());
                    
                    String cxy3=table.getModel().getValueAt(filaES, 8).toString();
                        if(cxy.equals("")){
                             Date fvaciaxy=null;
                            ActualizarMP.datefp.setDate(fvaciaxy); 
                            ActualizarMP.txt3.setText("");
                        }else{
                           try {
                                    FechaE = new SimpleDateFormat("yyyy-MM-dd").parse((String)table.getValueAt(filaES, 8).toString());
                                } catch (ParseException ex) {
                                    Logger.getLogger(RegistMP.class.getName()).log(Level.SEVERE, null, ex);
                                }
                  ActualizarMP.datefp.setDate(FechaE);
                        }
                    
                    
                    ActualizarMP.txtplaca.setText(table.getValueAt(filaES, 9).toString());
                    ActualizarMP.txtcliente.setText(table.getValueAt(filaES, 10).toString());
                    ActualizarMP.txtobra.setText(table.getValueAt(filaES, 11).toString());
                    
                     String turno = (String) table.getValueAt(filaES, 12);
                     ActualizarMP.cvturno.getModel().setSelectedItem(turno);
                     
                       String tc = (String) table.getValueAt(filaES, 13);
                     ActualizarMP.cbtc.getModel().setSelectedItem(tc);
          
                    
                    ActualizarMP.txtconsumo.setText(table.getValueAt(filaES, 14).toString());
                    
                       String m = (String) table.getValueAt(filaES, 15);
                     ActualizarMP.cbmedicion.getModel().setSelectedItem(m);
                    
                    ActualizarMP.txtcomienzo.setText(table.getValueAt(filaES, 16).toString());
                    ActualizarMP.txttermino.setText(table.getValueAt(filaES, 17).toString());
                    ActualizarMP.txtht.setText(table.getValueAt(filaES, 18).toString());
                    ActualizarMP.txtviaje.setText(table.getValueAt(filaES, 19).toString());
                    ActualizarMP.txtobs.setText(table.getValueAt(filaES, 20).toString());
                    ActualizarMP.txtsupervisor.setText(table.getValueAt(filaES, 21).toString());
                    
                    ActualizarMP.txtfmodif1.setText(table.getValueAt(filaES, 22).toString());
                    ActualizarMP.txtuser2.setText(table.getValueAt(filaES, 23).toString());
                    ActualizarMP.txtip1.setText(table.getValueAt(filaES, 24).toString());
  
            }
    }
}
